//! `app_control` strings of the CLI catalog (English and Japanese).

/// `cmux app|action|settings|window|events` and action verbs: the scopes the
/// cmux app owns (cli/app.rs).
#[derive(Debug, PartialEq, Eq)]
pub(crate) struct AppControlMessages {
    pub action_describe_usage: &'static str,
    pub action_run_usage: &'static str,
    pub settings_usage: &'static str,
    pub settings_confirm_hint: &'static str,
    pub settings_declined: &'static str,
    pub settings_waiting: &'static str,
    pub events_after_invalid: &'static str,
    pub scope_usage: &'static str,
    pub not_a_verb: &'static str,
    pub handles_unstable: &'static str,
    pub unexpected_argument: &'static str,
    pub missing_value: &'static str,
    pub arg_shape: &'static str,
    pub no_app: &'static str,
    pub unreachable: &'static str,
    pub timeout: &'static str,
    pub closed: &'static str,
    pub invalid_response: &'static str,
    pub root_scopes: &'static str,
    pub acp_open_usage: &'static str,
    pub chats_open_usage: &'static str,
    pub browser_page_usage: &'static str,
    pub keybinding_usage: &'static str,
    pub search_text_usage: &'static str,
    pub app_call_usage: &'static str,
    pub app_call_bad_json: &'static str,
    pub app_call_debug_only: &'static str,
    pub skew_classic: &'static str,
    pub skew_other: &'static str,
    pub skew_use_cli: &'static str,
}

pub(super) const ENGLISH: AppControlMessages = AppControlMessages {
    action_describe_usage: "usage: cmux action describe <action id or CLI name>",
    action_run_usage: "usage: cmux action run <action id or CLI name> [--target ID] [--<argument> VALUE]... [--wait]",
    settings_usage: "usage: cmux settings get [PATH] | set PATH VALUE [--confirm] | reset PATH [--confirm] | unset PATH [--confirm]",
    settings_confirm_hint: "add --confirm to ask for approval in cmux",
    settings_declined: "declined in cmux",
    settings_waiting: "Waiting for approval in cmux (Ctrl-C cancels this command; answer the sheet in cmux)",
    events_after_invalid: "--after needs an event sequence number, not \"{value}\"",
    scope_usage: "usage: cmux {scope} <action>; `cmux action list --noun {scope}` lists the actions",
    not_a_verb: "`cmux {name}` is not a CLI verb; run it with: cmux action run {id}",
    handles_unstable: "account handles change after restart: Keychain unavailable",
    unexpected_argument: "unexpected argument \"{value}\"",
    missing_value: "{flag} needs a value",
    arg_shape: "--arg needs NAME=VALUE, not \"{value}\"",
    no_app: "no cmux app found: run this inside a cmux terminal, use the cmux bundled in the app, or pass --app-socket PATH",
    unreachable: "the cmux app is not running at {path} ({error})",
    timeout: "the cmux app did not answer within {seconds} s",
    closed: "the cmux app closed the connection without an answer",
    invalid_response: "the cmux app sent an answer this cmux cannot read",
    acp_open_usage: "usage: cmux acp open SESSION [--pane PANE]",
    chats_open_usage: "usage: cmux chats open HARNESS:SESSION_ID [--cwd DIR]; `cmux chats list` shows the keys",
    browser_page_usage: "usage: cmux browser <tab_…|page> navigate URL | back | forward | reload | state | eval SCRIPT | snapshot [--selector S] [--max-depth N] [--interactive] | click|focus|text|value SELECTOR | fill|type SELECTOR TEXT",
    app_call_usage: "usage: cmux [--app-socket PATH] app call METHOD [JSON_OBJECT] (debug builds only)",
    app_call_bad_json: "app call: the params must be one JSON object, for example '{\"window\":\"win_1\"}'",
    app_call_debug_only: "app call works only with a DEV or tagged debug build's socket; this app is {bundle}",
    skew_classic: "this cmux-next CLI ({cli}) sent {method}, but the app at {socket} is the classic cmux app{version}, which does not speak cmux-next methods. Run this in a cmux-next terminal, or use the classic app's own CLI.",
    skew_other: "this CLI ({cli}) sent {method}, but {app}{version} at {socket} does not support it. Update and relaunch {app}, or use the CLI that ships with it.",
    skew_use_cli: "Its CLI: {path}",
    search_text_usage: "usage: cmux {scope} search <text> [OPTIONS]; `cmux {scope} --help` lists the options",
    keybinding_usage: "usage: cmux keybinding list [--query TEXT] [--command ID] [--source default|app|user] | resolve KEYS [--window ID] | context [--window ID]",
    root_scopes: "APP SCOPES (the cmux app)\n  app           ping, identify, capabilities, call (debug builds), and app actions (`cmux app new-window`)\n  window        List the app's windows\n  action        List, describe, and run registered actions\n  settings      Read and change cmux.json settings\n  events        Stream app events as JSON lines\n  history       List and search the app's history (list, search <text>)\n  bookmark      List and search browser bookmarks (list, search <text>)\n  keybinding    Read key bindings (list, resolve <keys>, context)\n  <noun> <verb> Any action by its CLI name (`cmux action list`)\n  --app-socket <path>  Connect to an exact app control socket\n",
};

pub(super) const JAPANESE: AppControlMessages = AppControlMessages {
    action_describe_usage: "使い方: cmux action describe <アクション ID または CLI 名>",
    action_run_usage: "使い方: cmux action run <アクション ID または CLI 名> [--target ID] [--<引数> 値]... [--wait]",
    settings_usage: "使い方: cmux settings get [パス] | set パス 値 [--confirm] | reset パス [--confirm] | unset パス [--confirm]",
    settings_confirm_hint: "--confirm を付けると cmux で承認を求めます",
    settings_declined: "cmux で拒否されました",
    settings_waiting: "cmux での承認を待っています (Ctrl-C でこのコマンドを取り消します。cmux のシートで応答してください)",
    events_after_invalid: "--after にはイベント番号が必要です (「{value}」は不正)",
    scope_usage: "使い方: cmux {scope} <アクション>。`cmux action list --noun {scope}` で一覧を表示",
    not_a_verb: "`cmux {name}` は CLI の動詞ではありません。実行するには: cmux action run {id}",
    handles_unstable: "アカウントのハンドルは再起動後に変わります: キーチェーンを使用できません",
    unexpected_argument: "予期しない引数「{value}」",
    missing_value: "{flag} には値が必要です",
    arg_shape: "--arg には 名前=値 が必要です (「{value}」は不正)",
    no_app: "cmux アプリが見つかりません: cmux のターミナル内で実行するか、アプリ同梱の cmux を使うか、--app-socket パス を指定してください",
    unreachable: "cmux アプリが {path} で動作していません ({error})",
    timeout: "cmux アプリが {seconds} 秒以内に応答しませんでした",
    closed: "cmux アプリが応答せずに接続を閉じました",
    invalid_response: "cmux アプリの応答を読み取れません",
    acp_open_usage: "使い方: cmux acp open セッション [--pane ペイン]",
    chats_open_usage: "使い方: cmux chats open ハーネス:セッションID [--cwd フォルダ]。キーは `cmux chats list` で表示",
    browser_page_usage: "使い方: cmux browser <tab_…|page> navigate URL | back | forward | reload | state | eval スクリプト | snapshot [--selector S] [--max-depth N] [--interactive] | click|focus|text|value セレクタ | fill|type セレクタ テキスト",
    app_call_usage: "使い方: cmux [--app-socket パス] app call メソッド [JSON オブジェクト] (デバッグビルドのみ)",
    app_call_bad_json: "app call: パラメータは 1 つの JSON オブジェクトにしてください (例: '{\"window\":\"win_1\"}')",
    app_call_debug_only: "app call は DEV またはタグ付きデバッグビルドのソケットでのみ使えます。このアプリは {bundle} です",
    skew_classic: "この cmux-next CLI ({cli}) は {method} を送りましたが、{socket} のアプリは従来の cmux アプリ{version} で、cmux-next のメソッドを話しません。cmux-next のターミナルで実行するか、従来のアプリ自身の CLI を使ってください。",
    skew_other: "この CLI ({cli}) は {method} を送りましたが、{socket} の {app}{version} はこのメソッドに対応していません。{app} を更新して再起動するか、そのアプリに同梱された CLI を使ってください。",
    skew_use_cli: "その CLI: {path}",
    search_text_usage: "使い方: cmux {scope} search <テキスト> [オプション]。オプションは `cmux {scope} --help` で表示",
    keybinding_usage: "使い方: cmux keybinding list [--query テキスト] [--command ID] [--source default|app|user] | resolve キー [--window ID] | context [--window ID]",
    root_scopes: "アプリのスコープ (cmux アプリ)\n  app           ping、identify、capabilities、call (デバッグビルド) とアプリのアクション (`cmux app new-window`)\n  window        アプリのウィンドウ一覧\n  action        登録済みアクションの一覧、説明、実行\n  settings      cmux.json の設定の読み取りと変更\n  events        アプリのイベントを JSON 行で表示\n  history       アプリの履歴の一覧と検索 (list、search <テキスト>)\n  bookmark      ブラウザのブックマークの一覧と検索 (list、search <テキスト>)\n  keybinding    キーバインドの読み取り (list、resolve <キー>、context)\n  <名詞> <動詞> CLI 名で任意のアクションを実行 (`cmux action list`)\n  --app-socket <パス>  指定したアプリ制御ソケットに接続\n",
};
