#!/usr/bin/env bash
# scripts/cmux-next/check-daemon-capabilities-fresh.py compares the capability
# lists in DaemonEndpoint.swift with plans/cmux-next/daemon-capabilities.json
# without a build. 67b13e24e84d moved sidebar-layout-v1 from
# unservedByBundledDaemon to optional in Swift only; the stale JSON failed
# every tagged build (2026-10-07).
set -euo pipefail

check="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/check-daemon-capabilities-fresh.py"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
fail() { echo "FAIL: $*" >&2; exit 1; }
swift="$tmp/Packages/macOS/CmuxNext/Sources/CmuxNextDaemon/Connection/DaemonEndpoint.swift"
json="$tmp/plans/cmux-next/daemon-capabilities.json"
mkdir -p "$(dirname "$swift")" "$(dirname "$json")"

write_swift() { # optional-identifiers unserved-identifiers
  cat > "$swift" <<EOF
public struct DaemonEndpoint: Sendable {
    public var socketPath: String
}

public struct DaemonCapabilities: Sendable {
    public static let shared = Self()
    public let required: [String] = [
        "workspace-registry-v1",
        "attach-initial-size",
    ]

    /// Docs with a "quoted-v1" word and a [bracket].
    public let workspaceGroups = "workspace-groups-v1"
    public let sidebarLayout = "sidebar-layout-v1"
    public let remoteTerminalTabs = "remote-terminal-tabs-v1"

    public var homeOnly: [String] { [workspaceGroups] }
    public var optional: [String] { [$1] }
    public var unservedByBundledDaemon: [String] { [$2] }
}
EOF
}
write_json() { # optional-json unserved-json
  cat > "$json" <<EOF
{
  "comment" : "Generated by DaemonCapabilityExportTests from DaemonCapabilities; read by scripts/cmux-next/check-daemon-capabilities.sh.",
  "optional" : [$1],
  "required" : ["attach-initial-size", "workspace-registry-v1"],
  "unservedByBundledDaemon" : [$2]
}
EOF
}
run() { python3 "$check" --repo "$tmp" 2>&1; }

write_swift "workspaceGroups" "remoteTerminalTabs, sidebarLayout"
write_json '"workspace-groups-v1"' '"remote-terminal-tabs-v1", "sidebar-layout-v1"'
out="$(run)" || fail "a fresh export failed: $out"

# 67b13e24e84d: Swift moves sidebar-layout-v1 to optional, the JSON stays.
write_swift "workspaceGroups,
                                       sidebarLayout" "remoteTerminalTabs"
if out="$(run)"; then fail "a Swift-only move passed: $out"; fi
[[ "$out" == *"sidebar-layout-v1"* ]] || fail "the failure does not name sidebar-layout-v1: $out"
[[ "$out" == *"CMUX_UPDATE_DAEMON_CAPABILITIES=1"* ]] || fail "the failure lacks the regenerate command: $out"

# The JSON regenerated with it passes again.
write_json '"sidebar-layout-v1", "workspace-groups-v1"' '"remote-terminal-tabs-v1"'
out="$(run)" || fail "the regenerated export failed: $out"

# An identifier the parser cannot resolve fails loudly instead of being skipped.
write_swift "workspaceGroups, sidebarLayout, someComputedThing" "remoteTerminalTabs"
if out="$(run)"; then fail "an unresolved identifier passed: $out"; fi
[[ "$out" == *"someComputedThing"* ]] || fail "the failure does not name the unresolved identifier: $out"

echo "daemon-capabilities-fresh.test.sh: ok"
