//! systemd units (server.md 4.3, 7.4).
//!
//! The main unit runs the frozen `cmux host run` with `Type=notify` (it
//! sends `READY=1` when the session host answers) and `KillMode=process`
//! (terminal hosts survive a restart). It is not hardened with
//! `ProtectHome`, `NoNewPrivileges` or read-only mounts, because the
//! terminals it hosts are ordinary shells that need home directories and
//! `sudo`. App servers get the strict hardening in their own template unit.
//! In system mode the store is root-owned and updated only by the root
//! oneshot `cmux-update.service`, started by `cmux-update.path` when the
//! supervisor writes the update request (no timer).

use super::{SERVICE_USER, UnitError};
use crate::layout::{Layout, UPDATE_REQUEST};
use crate::platform::{InstallMode, Platform};

/// systemd `ExecStart` quoting: the path in double quotes. Characters that
/// systemd would expand or that need escaping are refused.
fn exec_path(layout: &Layout) -> Result<String, UnitError> {
    let path = layout.current_cmux.as_str();
    if path.chars().any(|c| c.is_control() || matches!(c, '"' | '\\' | '$' | '%' | ';')) {
        return Err(UnitError::UnsafePath("current_cmux"));
    }
    Ok(format!("\"{path}\""))
}

/// `~/.config/systemd/user/cmux-server.service`. Needs linger to run
/// without a login session.
pub fn systemd_user_unit(layout: &Layout) -> Result<String, UnitError> {
    if layout.platform != Platform::Linux || layout.mode != InstallMode::User {
        return Err(UnitError::WrongLayout);
    }
    let exec = exec_path(layout)?;
    Ok(format!(
        "# Generated by cmux. Do not edit: `cmux server install` rewrites this file.
[Unit]
Description=cmux server
Documentation=https://cmux.com/docs/server
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
NotifyAccess=main
ExecStart={exec} host run --mode user
Restart=always
RestartSec=2
# The session host keeps its terminal hosts across a restart: stop only the
# supervisor process (lane 1 handoff contract).
KillMode=process
TimeoutStopSec=30

[Install]
WantedBy=default.target
"
    ))
}

/// `/etc/systemd/system/cmux-server.service`, running as user `cmux`.
pub fn systemd_system_unit(layout: &Layout) -> Result<String, UnitError> {
    linux_system(layout)?;
    let exec = exec_path(layout)?;
    Ok(format!(
        "# Generated by cmux. Do not edit: `cmux server install --system` rewrites this file.
[Unit]
Description=cmux server
Documentation=https://cmux.com/docs/server
Wants=network-online.target cmux-update.path
After=network-online.target

[Service]
Type=notify
NotifyAccess=main
User={SERVICE_USER}
Group={SERVICE_USER}
ExecStart={exec} host run --mode system
Restart=always
RestartSec=2
KillMode=process
TimeoutStopSec=30
StateDirectory=cmux
StateDirectoryMode=0700
RuntimeDirectory=cmux
RuntimeDirectoryMode=0755
RuntimeDirectoryPreserve=yes
ConfigurationDirectory=cmux
UMask=0027

[Install]
WantedBy=multi-user.target
"
    ))
}

fn linux_system(layout: &Layout) -> Result<(), UnitError> {
    if layout.platform != Platform::Linux || layout.mode != InstallMode::System {
        return Err(UnitError::WrongLayout);
    }
    Ok(())
}

/// `/etc/systemd/system/cmux-update.path`: starts the root updater when
/// the supervisor writes the update request. The updater deletes the
/// request when it finishes, so `PathExists` fires once per request and
/// again at boot for a request left by a crash.
pub fn systemd_update_path_unit(layout: &Layout) -> Result<String, UnitError> {
    linux_system(layout)?;
    Ok(format!(
        "# Generated by cmux. Do not edit: `cmux server install --system` rewrites this file.
[Unit]
Description=Start the cmux updater when the server asks for an update

[Path]
PathExists={UPDATE_REQUEST}
Unit=cmux-update.service

[Install]
WantedBy=multi-user.target
"
    ))
}

/// `/etc/systemd/system/cmux-update.service`: the only process that writes
/// the root-owned store. It runs as root, treats the request as untrusted
/// input (the cmux user wrote it), and applies only a manifest that verifies
/// against the baked keys.
pub fn systemd_update_service_unit(layout: &Layout) -> Result<String, UnitError> {
    linux_system(layout)?;
    let exec = exec_path(layout)?;
    let root = layout.root.as_str();
    if root
        .chars()
        .any(|c| c.is_control() || c.is_whitespace() || matches!(c, '"' | '\\' | '$' | '%'))
    {
        return Err(UnitError::UnsafePath("root"));
    }
    Ok(format!(
        "# Generated by cmux. Do not edit: `cmux server install --system` rewrites this file.
[Unit]
Description=cmux store update (root, on request)
Documentation=https://cmux.com/docs/server
ConditionPathExists={UPDATE_REQUEST}

[Service]
Type=oneshot
ExecStart={exec} host update --request {UPDATE_REQUEST}
UMask=0022
NoNewPrivileges=yes
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=strict
ReadWritePaths={root} /run/cmux
"
    ))
}

/// `/etc/systemd/system/cmux-app-server@.service`: one app server per
/// instance (`%i` is the mapped app id, `pg::AppId`), started only by the
/// supervisor after the lease assignment, so it has no `[Install]`
/// section. Memory and CPU limits per app come from a drop-in the
/// supervisor writes; the values here are the defaults.
pub fn systemd_app_server_template(layout: &Layout) -> Result<String, UnitError> {
    linux_system(layout)?;
    let exec = exec_path(layout)?;
    let state = layout.state.as_str();
    if state
        .chars()
        .any(|c| c.is_control() || c.is_whitespace() || matches!(c, '"' | '\\' | '$' | '%'))
    {
        return Err(UnitError::UnsafePath("state"));
    }
    Ok(format!(
        "# Generated by cmux. Do not edit: `cmux server install --system` rewrites this file.
[Unit]
Description=cmux app server %i
Documentation=https://cmux.com/docs/server

[Service]
Type=exec
User=app-%i
Group=app-%i
SupplementaryGroups=cmux-db
ExecStart={exec} host app-server %i
Restart=no
MemoryMax=512M
CPUQuota=100%
UMask=0077
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectHome=yes
ProtectSystem=strict
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
LockPersonality=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
ReadWritePaths={state}/apps/%i /run/cmux/apps/%i
"
    ))
}
