//! Generates `crates/cmux-vm-client/src/generated.rs` from the cmux VM
//! OpenAPI document. Run it through `scripts/regenerate.sh`, never by hand:
//! CI reruns that script and fails when the checked-in file differs.
//!
//!   cmux-vm-codegen --spec <openapi.json> --out <generated.rs> \
//!     --raw-out <generated_raw.rs> --label <text>
//!
//! `--out` gets the typed client. `--raw-out` gets the same client with every
//! success body returned as raw bytes, for callers (the CLI's `--json`) that
//! must pass the server's response through unchanged, unknown fields included.

mod normalize;

use std::path::PathBuf;
use std::process::{Command, ExitCode};

struct Args {
    spec: PathBuf,
    out: PathBuf,
    raw_out: PathBuf,
    label: String,
}

fn parse_args() -> Result<Args, String> {
    let mut spec = None;
    let mut out = None;
    let mut raw_out = None;
    let mut label = None;
    let mut args = std::env::args().skip(1);
    while let Some(flag) = args.next() {
        let value = args.next().ok_or_else(|| format!("{flag} needs a value"))?;
        match flag.as_str() {
            "--spec" => spec = Some(PathBuf::from(value)),
            "--out" => out = Some(PathBuf::from(value)),
            "--raw-out" => raw_out = Some(PathBuf::from(value)),
            "--label" => label = Some(value),
            other => return Err(format!("unknown argument {other}")),
        }
    }
    Ok(Args {
        spec: spec.ok_or("--spec is required")?,
        out: out.ok_or("--out is required")?,
        raw_out: raw_out.ok_or("--raw-out is required")?,
        label: label.ok_or("--label is required")?,
    })
}

fn generate(args: &Args) -> Result<(), String> {
    let text = std::fs::read_to_string(&args.spec)
        .map_err(|e| format!("read {}: {e}", args.spec.display()))?;
    let mut doc: serde_json::Value =
        serde_json::from_str(&text).map_err(|e| format!("parse {}: {e}", args.spec.display()))?;
    normalize::normalize(&mut doc);
    emit(doc.clone(), &args.out, &args.label, &args.spec)?;
    normalize::raw_success_bodies(&mut doc);
    emit(doc, &args.raw_out, &args.label, &args.spec)
}

fn emit(
    doc: serde_json::Value,
    out: &std::path::Path,
    label: &str,
    spec_path: &std::path::Path,
) -> Result<(), String> {
    let spec: openapiv3::OpenAPI = serde_json::from_value(doc).map_err(|e| {
        format!(
            "{} is not an OpenAPI 3.0 document after normalization: {e}",
            spec_path.display()
        )
    })?;

    let settings = progenitor::GenerationSettings::default();
    let mut generator = progenitor::Generator::new(&settings);
    let tokens = generator
        .generate_tokens(&spec)
        .map_err(|e| format!("progenitor: {e}"))?;
    let file: syn::File =
        syn::parse2(tokens).map_err(|e| format!("generated code does not parse: {e}"))?;
    let body = prettyplease::unparse(&file);

    let header = format!(
        "// @generated by cmux-vm-codegen from {label}. Do not edit; run\n\
         // workers/cmux-vm/cli/scripts/regenerate.sh instead.\n\n"
    );
    std::fs::write(out, format!("{header}{body}"))
        .map_err(|e| format!("write {}: {e}", out.display()))?;

    // rustfmt after prettyplease, so `cargo fmt --check` accepts the file.
    let status = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(out)
        .status()
        .map_err(|e| format!("run rustfmt: {e}"))?;
    if !status.success() {
        return Err(format!("rustfmt failed on {}", out.display()));
    }
    Ok(())
}

fn main() -> ExitCode {
    match parse_args().and_then(|args| generate(&args)) {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("cmux-vm-codegen: {message}");
            ExitCode::FAILURE
        }
    }
}
