//! Postgres plan goldens, injection refusal, schema vs database mode.

use cmux_server_core::pg::{
    AppDb, AppId, AppIdError, AppLimits, ClusterSpec, DbMode, PgError, PgPlan, admin_pgpass_line,
    password_from_random, pgpass_line, quote_ident, quote_literal, scram_verifier,
};
use cmux_server_core::{HostPath, InstallMode, Platform};
use proptest::prelude::*;

fn p(platform: Platform, s: &str) -> HostPath {
    HostPath::new(platform, s).unwrap()
}

fn linux_spec(mode: InstallMode) -> ClusterSpec {
    let (state, user) = match mode {
        InstallMode::User => ("/home/ana/.local/state/cmux/server", "ana"),
        InstallMode::System => ("/var/lib/cmux", "cmux"),
    };
    let socket = match mode {
        InstallMode::User => format!("{state}/postgres/run"),
        InstallMode::System => "/run/cmux/postgres".to_owned(),
    };
    ClusterSpec {
        mode,
        platform: Platform::Linux,
        pg_bin_dir: p(Platform::Linux, "/opt/cmux/current/lib/postgresql-17/bin"),
        data_dir: p(Platform::Linux, &format!("{state}/postgres/17/data")),
        socket_dir: p(Platform::Linux, &socket),
        port: 17274,
        cmux_bin: p(Platform::Linux, "/opt/cmux/current/bin/cmux"),
        service_user: user.to_owned(),
        // User mode: the admin uses SCRAM with a secret (server.md 8.3).
        admin_pwfile: (mode == InstallMode::User)
            .then(|| p(Platform::Linux, &format!("{state}/postgres/initdb.pw"))),
    }
}

fn windows_spec() -> ClusterSpec {
    let w = |s: &str| p(Platform::Windows, s);
    ClusterSpec {
        mode: InstallMode::User,
        platform: Platform::Windows,
        pg_bin_dir: w(r"C:\Users\ana\AppData\Local\cmux\current\pg\bin"),
        data_dir: w(r"C:\Users\ana\AppData\Local\cmux\server\postgres\17\data"),
        socket_dir: w(r"C:\Users\ana\AppData\Local\cmux\server\postgres\run"),
        port: 17274,
        cmux_bin: w(r"C:\Users\ana\AppData\Local\cmux\current\bin\cmux.exe"),
        service_user: "ana".to_owned(),
        admin_pwfile: Some(w(r"C:\Users\ana\AppData\Local\cmux\server\postgres\admin.pw")),
    }
}

fn app(id: &str, mode: DbMode, tcp: bool) -> AppDb {
    AppDb { id: AppId::parse(id).unwrap(), mode, tcp }
}

#[test]
fn initdb_argv_unix_and_windows() {
    let plan = PgPlan::new(linux_spec(InstallMode::System)).unwrap();
    assert_eq!(
        plan.initdb_argv(),
        [
            "/opt/cmux/current/lib/postgresql-17/bin/initdb",
            "--pgdata=/var/lib/cmux/postgres/17/data",
            "--data-checksums",
            "--encoding=UTF8",
            "--locale=C",
            "--locale-provider=builtin",
            "--builtin-locale=C.UTF-8",
            "--auth-local=peer",
            "--auth-host=reject",
            "--username=cmux_admin",
        ]
    );
    let user = PgPlan::new(linux_spec(InstallMode::User)).unwrap().initdb_argv();
    assert_eq!(
        user[7..],
        [
            "--auth-local=scram-sha-256",
            "--auth-host=reject",
            "--pwfile=/home/ana/.local/state/cmux/server/postgres/initdb.pw",
            "--username=cmux_admin",
        ]
    );
    let win = PgPlan::new(windows_spec()).unwrap();
    let argv = win.initdb_argv();
    assert_eq!(argv[0], r"C:\Users\ana\AppData\Local\cmux\current\pg\bin\initdb.exe");
    assert!(argv.contains(&"--auth-local=scram-sha-256".to_owned()));
    assert!(argv.contains(&"--auth-host=reject".to_owned()));
    assert!(argv.contains(
        &r"--pwfile=C:\Users\ana\AppData\Local\cmux\server\postgres\admin.pw".to_owned()
    ));
}

#[test]
fn postgresql_conf_golden_user_mode() {
    let plan = PgPlan::new(linux_spec(InstallMode::User)).unwrap();
    assert_eq!(
        plan.postgresql_conf(&[app("notes", DbMode::Database, false)]),
        "# Generated by cmux (server.md 8). Do not edit: cmux rewrites this file.
listen_addresses = ''
port = 17274
unix_socket_directories = '\"/home/ana/.local/state/cmux/server/postgres/run\"'
unix_socket_permissions = 0700
password_encryption = 'scram-sha-256'
standard_conforming_strings = on
wal_level = replica
archive_mode = on
archive_timeout = 60
archive_command = '\"/opt/cmux/current/bin/cmux\" server db archive-wal \"%p\" \"%f\"'
"
    );
}

#[test]
fn postgresql_conf_system_mode_and_tcp() {
    let plan = PgPlan::new(linux_spec(InstallMode::System)).unwrap();
    let conf = plan.postgresql_conf(&[app("notes", DbMode::Database, true)]);
    assert!(conf.contains("listen_addresses = '127.0.0.1'\n"));
    assert!(conf.contains("unix_socket_directories = '\"/run/cmux/postgres\"'\n"));
    assert!(conf.contains("unix_socket_group = 'cmux-db'\nunix_socket_permissions = 0770\n"));
    let win = PgPlan::new(windows_spec()).unwrap().postgresql_conf(&[]);
    assert!(win.contains("listen_addresses = '127.0.0.1'\n"));
    assert!(win.contains("unix_socket_directories = ''\n"));
    // Backslashes are doubled inside postgresql.conf strings.
    assert!(win.contains(
        r#"archive_command = '"C:\\Users\\ana\\AppData\\Local\\cmux\\current\\bin\\cmux.exe" server db archive-wal "%p" "%f"'"#
    ));
}

#[test]
fn hba_and_ident_golden_system_mode() {
    let plan = PgPlan::new(linux_spec(InstallMode::System)).unwrap();
    let apps = [app("notes", DbMode::Database, false), app("crm", DbMode::Schema, true)];
    assert_eq!(
        plan.pg_hba_conf(&apps),
        "# Generated by cmux (server.md 8). Do not edit: cmux rewrites this file.
# TYPE DATABASE USER ADDRESS METHOD
local all cmux_admin peer map=cmuxadmin
local replication cmux_admin peer map=cmuxadmin
local sameuser app_notes peer map=cmuxapps
local cmux_apps app_crm peer map=cmuxapps
host cmux_apps app_crm 127.0.0.1/32 scram-sha-256
local all all reject
host all all all reject
"
    );
    assert_eq!(
        plan.pg_ident_conf(&apps),
        "# Generated by cmux (server.md 8). Do not edit: cmux rewrites this file.
# MAPNAME SYSTEM-USERNAME PG-USERNAME
cmuxadmin cmux cmux_admin
cmuxapps app-notes app_notes
cmuxapps app-crm app_crm
"
    );
}

#[test]
fn hba_user_mode_and_windows() {
    let plan = PgPlan::new(linux_spec(InstallMode::User)).unwrap();
    let apps = [app("notes", DbMode::Database, false)];
    let hba = plan.pg_hba_conf(&apps);
    // User mode: no peer at all, so a same-user app cannot become admin.
    assert!(hba.ends_with(
        "# TYPE DATABASE USER ADDRESS METHOD
local all cmux_admin scram-sha-256
local replication cmux_admin scram-sha-256
local sameuser app_notes scram-sha-256
local all all reject
host all all all reject
"
    ));
    assert!(!hba.contains("peer"));
    assert!(plan.pg_ident_conf(&apps).ends_with("# MAPNAME SYSTEM-USERNAME PG-USERNAME\n"));
    let win = PgPlan::new(windows_spec()).unwrap();
    let hba = win.pg_hba_conf(&apps);
    assert!(hba.contains(
        "\nhost all cmux_admin 127.0.0.1/32 scram-sha-256\nhost replication cmux_admin 127.0.0.1/32 scram-sha-256\nhost sameuser app_notes 127.0.0.1/32 scram-sha-256\n"
    ));
    assert!(!hba.contains("peer"));
    assert!(hba.ends_with("host all all all reject\n"));
}

#[test]
fn app_sql_database_mode_system() {
    let plan = PgPlan::new(linux_spec(InstallMode::System)).unwrap();
    let a = app("notes", DbMode::Database, false);
    assert!(!plan.app_needs_password(&a));
    let sql = plan.app_sql(&a, &AppLimits::default(), None).unwrap();
    let rendered: Vec<(&str, &str)> =
        sql.iter().map(|s| (s.database.as_str(), s.sql.as_str())).collect();
    assert_eq!(
        rendered,
        [
            (
                "postgres",
                "CREATE ROLE \"app_notes\" LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT CONNECTION LIMIT 20"
            ),
            ("postgres", "ALTER ROLE \"app_notes\" SET statement_timeout = '30000ms'"),
            (
                "postgres",
                "ALTER ROLE \"app_notes\" SET idle_in_transaction_session_timeout = '60000ms'"
            ),
            ("postgres", "ALTER ROLE \"app_notes\" SET temp_file_limit = '1048576kB'"),
            (
                "postgres",
                "CREATE DATABASE \"app_notes\" OWNER \"app_notes\" TEMPLATE \"template0\""
            ),
            ("postgres", "REVOKE ALL ON DATABASE \"app_notes\" FROM PUBLIC"),
            ("app_notes", "REVOKE CREATE ON SCHEMA \"public\" FROM PUBLIC"),
        ]
    );
    // A verifier where none is needed is refused (no silent password).
    assert_eq!(
        plan.app_sql(&a, &AppLimits::default(), Some("SCRAM-SHA-256$1:a$b:c")),
        Err(PgError::BadVerifier)
    );
}

#[test]
fn app_sql_schema_mode_user_with_password() {
    let plan = PgPlan::new(linux_spec(InstallMode::User)).unwrap();
    let a = app("crm", DbMode::Schema, false);
    assert!(plan.app_needs_password(&a));
    assert_eq!(plan.app_sql(&a, &AppLimits::default(), None), Err(PgError::BadVerifier));
    let v = scram_verifier(&password_from_random(&[7; 32]), &[1; 16], 4096).unwrap();
    let sql = plan.app_sql(&a, &AppLimits::default(), Some(&v)).unwrap();
    assert!(sql[0].sql.ends_with(&format!("CONNECTION LIMIT 20 PASSWORD '{v}'")));
    let tail: Vec<(&str, &str)> =
        sql[4..].iter().map(|s| (s.database.as_str(), s.sql.as_str())).collect();
    assert_eq!(
        tail,
        [
            ("postgres", "GRANT CONNECT ON DATABASE \"cmux_apps\" TO \"app_crm\""),
            ("cmux_apps", "CREATE SCHEMA \"app_crm\" AUTHORIZATION \"app_crm\""),
            ("cmux_apps", "REVOKE ALL ON SCHEMA \"app_crm\" FROM PUBLIC"),
            (
                "postgres",
                "ALTER ROLE \"app_crm\" IN DATABASE \"cmux_apps\" SET search_path = \"app_crm\""
            ),
        ]
    );
    let shared: Vec<String> = plan.shared_database_sql().into_iter().map(|s| s.sql).collect();
    assert_eq!(
        shared[0],
        "CREATE DATABASE \"cmux_apps\" OWNER \"cmux_admin\" TEMPLATE \"template0\""
    );
    assert_eq!(plan.cluster_sql().len(), 2);
    assert_eq!(
        plan.advisory_read_only_sql(&a, true).sql,
        "ALTER ROLE \"app_crm\" SET default_transaction_read_only = on"
    );
}

#[test]
fn verifier_injection_is_refused() {
    let plan = PgPlan::new(linux_spec(InstallMode::User)).unwrap();
    let a = app("crm", DbMode::Database, false);
    for bad in
        ["x", "SCRAM-SHA-256$4096:a$b:c'; DROP ROLE cmux_admin; --", "SCRAM-SHA-256$", "md5abc"]
    {
        assert_eq!(
            plan.app_sql(&a, &AppLimits::default(), Some(bad)),
            Err(PgError::BadVerifier),
            "{bad}"
        );
    }
}

#[test]
fn scram_verifier_golden() {
    let password = password_from_random(&std::array::from_fn(|i| i as u8));
    assert_eq!(password, "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f");
    let salt: [u8; 16] = std::array::from_fn(|i| i as u8);
    assert_eq!(
        scram_verifier(&password, &salt, 4096).unwrap(),
        "SCRAM-SHA-256$4096:AAECAwQFBgcICQoLDA0ODw==$poBvrHTZHMXdX1FqZ+R0BrW8cHgi6K4DshN9FcJHVCo=:M4BrcI1FUEX0G77OsfQBkLR75In22riA17sfy+TLnIY="
    );
    assert_eq!(scram_verifier("tab\there", &salt, 4096), None);
    assert_eq!(scram_verifier("x", &salt, 0), None);
    assert_eq!(admin_pgpass_line("p:w"), "*:*:*:cmux_admin:p\\:w\n");
    assert_eq!(
        pgpass_line(&app("crm", DbMode::Schema, false), "a:b\\c"),
        "*:*:cmux_apps:app_crm:a\\:b\\\\c\n"
    );
}

#[test]
fn app_ids_refuse_injection() {
    let cases: [(&str, AppIdError); 9] = [
        ("", AppIdError::Empty),
        ("Notes", AppIdError::BadStart),
        ("1notes", AppIdError::BadStart),
        ("_notes", AppIdError::BadStart),
        ("notes\"; DROP ROLE cmux_admin; --", AppIdError::BadChar(5)),
        ("no tes", AppIdError::BadChar(2)),
        ("notes-app", AppIdError::BadChar(5)),
        ("nötes", AppIdError::BadChar(1)),
        ("a23456789012345678901234567890123456789012", AppIdError::TooLong(42)),
    ];
    for (input, err) in cases {
        assert_eq!(AppId::parse(input), Err(err), "{input:?}");
    }
    let max = "a2345678901234567890123456789012345678901";
    assert_eq!(AppId::parse(max).unwrap().role().len(), 45);
    assert_eq!(quote_ident("a\"b").unwrap(), "\"a\"\"b\"");
    assert_eq!(quote_ident("a\0b"), None);
    assert_eq!(quote_literal("it's").unwrap(), "'it''s'");
}

#[test]
fn unsafe_specs_are_refused() {
    let mut s = linux_spec(InstallMode::User);
    s.cmux_bin = p(Platform::Linux, "/opt/cmux/$(reboot)/cmux");
    assert_eq!(PgPlan::new(s), Err(PgError::UnsafePath("cmux_bin")));
    let mut s = linux_spec(InstallMode::User);
    s.socket_dir = p(Platform::Linux, "/tmp/it's");
    assert_eq!(PgPlan::new(s), Err(PgError::UnsafePath("socket_dir")));
    let mut s = linux_spec(InstallMode::User);
    s.socket_dir = p(Platform::Linux, &format!("/{}", "d".repeat(90)));
    assert_eq!(PgPlan::new(s), Err(PgError::SocketPathTooLong(106)));
    let mut s = linux_spec(InstallMode::User);
    s.port = 5432;
    assert_eq!(PgPlan::new(s), Err(PgError::BadPort(5432)));
    let mut s = linux_spec(InstallMode::User);
    s.service_user = "ana; rm".to_owned();
    assert_eq!(PgPlan::new(s), Err(PgError::BadServiceUser));
    let mut s = windows_spec();
    s.admin_pwfile = None;
    assert_eq!(PgPlan::new(s), Err(PgError::PwfileMismatch));
    let mut s = linux_spec(InstallMode::User);
    s.admin_pwfile = None;
    assert_eq!(PgPlan::new(s), Err(PgError::PwfileMismatch));
    let mut s = linux_spec(InstallMode::System);
    s.admin_pwfile = Some(p(Platform::Linux, "/var/lib/cmux/postgres/initdb.pw"));
    assert_eq!(PgPlan::new(s), Err(PgError::PwfileMismatch));
    let mut s = linux_spec(InstallMode::User);
    s.data_dir = p(Platform::Windows, r"C:\data");
    assert_eq!(PgPlan::new(s), Err(PgError::UnsafePath("data_dir")));
}

proptest! {
    /// Any string either fails validation or yields identifiers made only of
    /// `[a-z0-9_]`, so nothing it renders can leave its quotes.
    #[test]
    fn app_id_parse_is_closed(id in "\\PC{0,48}") {
        if let Ok(app) = AppId::parse(&id) {
            prop_assert!(app.role().bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_'));
            let plan = PgPlan::new(linux_spec(InstallMode::System)).unwrap();
            let db = AppDb { id: app, mode: DbMode::Database, tcp: false };
            for s in plan.app_sql(&db, &AppLimits::default(), None).unwrap() {
                prop_assert!(!s.sql.contains(';'));
            }
        }
    }
}

#[test]
fn database_url_and_env_carry_no_password() {
    let plan = PgPlan::new(linux_spec(InstallMode::User)).unwrap();
    let notes = app("notes", DbMode::Database, false);
    assert_eq!(
        plan.database_url(&notes),
        "postgresql://app_notes@/app_notes?host=/home/ana/.local/state/cmux/server/postgres/run&port=17274"
    );
    let crm = app("crm", DbMode::Schema, true);
    assert_eq!(plan.database_url(&crm), "postgresql://app_crm@127.0.0.1:17274/cmux_apps");
    let env = plan.app_env(&notes);
    let names: Vec<&str> = env.iter().map(|(k, _)| *k).collect();
    assert_eq!(names, ["PGHOST", "PGPORT", "PGDATABASE", "PGUSER", "DATABASE_URL"]);
    assert_eq!(env[0].1, "/home/ana/.local/state/cmux/server/postgres/run");
    assert!(env.iter().all(|(k, _)| !k.contains("PASS")));
    // A socket directory with a space (a macOS state path) is percent-encoded.
    let mut spec = linux_spec(InstallMode::User);
    spec.socket_dir = p(Platform::Linux, "/tmp/a b/pg");
    let plan = PgPlan::new(spec).unwrap();
    assert!(plan.database_url(&notes).contains("host=/tmp/a%20b/pg&"));
    let windows = PgPlan::new(windows_spec()).unwrap();
    assert_eq!(windows.database_url(&notes), "postgresql://app_notes@127.0.0.1:17274/app_notes");
}

#[test]
fn app_sql_is_role_then_objects_and_password_reset_needs_scram() {
    let plan = PgPlan::new(linux_spec(InstallMode::User)).unwrap();
    let notes = app("notes", DbMode::Database, false);
    let limits = AppLimits::default();
    let v = scram_verifier("p", &[7u8; 16], 4096).unwrap();
    let all = plan.app_sql(&notes, &limits, Some(&v)).unwrap();
    let mut split = vec![plan.app_role_sql(&notes, &limits, Some(&v)).unwrap()];
    split.extend(plan.app_objects_sql(&notes, &limits));
    assert_eq!(all, split);
    let reset = plan.set_password_sql(&notes, &v).unwrap();
    assert!(reset.sql.starts_with("ALTER ROLE \"app_notes\" PASSWORD 'SCRAM-SHA-256$4096:"));
    assert_eq!(reset.database, "postgres");
    assert_eq!(plan.set_password_sql(&notes, "plain"), Err(PgError::BadVerifier));
    // Linux system mode: peer only, so no password may be set.
    let system = PgPlan::new(linux_spec(InstallMode::System)).unwrap();
    assert_eq!(system.set_password_sql(&notes, &v), Err(PgError::BadVerifier));
}
