//! Service definition goldens: every variant runs `<current>/bin/cmux host run`.

use cmux_server_core::layout::{Layout, LayoutEnv, layout};
use cmux_server_core::units::{
    UnitError, app_service_agent_plist, host_run_argv, host_run_argv_with_mode, launch_agent_plist,
    launch_daemon_plist, scheduled_task_xml, systemd_app_server_template, systemd_system_unit,
    systemd_update_path_unit, systemd_update_service_unit, systemd_user_unit,
    windows_service_create_argv, windows_service_failure_argv,
};
use cmux_server_core::{InstallMode, Platform};

fn unix(mode: InstallMode, platform: Platform, home: &str) -> Layout {
    let env = LayoutEnv { home: Some(home.to_owned()), uid: Some(501), ..LayoutEnv::default() };
    layout(mode, platform, &env).unwrap()
}

fn win(mode: InstallMode) -> Layout {
    let env = LayoutEnv {
        local_app_data: Some(r"C:\Users\ana\AppData\Local".to_owned()),
        app_data: Some(r"C:\Users\ana\AppData\Roaming".to_owned()),
        program_data: Some(r"C:\ProgramData".to_owned()),
        program_files: Some(r"C:\Program Files".to_owned()),
        ..LayoutEnv::default()
    };
    layout(mode, Platform::Windows, &env).unwrap()
}

#[test]
fn systemd_user_unit_golden() {
    let l = unix(InstallMode::User, Platform::Linux, "/home/ana");
    assert_eq!(host_run_argv(&l), ["/home/ana/.local/share/cmux/current/bin/cmux", "host", "run"]);
    assert_eq!(
        systemd_user_unit(&l).unwrap(),
        "# Generated by cmux. Do not edit: `cmux server install` rewrites this file.
[Unit]
Description=cmux server
Documentation=https://cmux.com/docs/server
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
NotifyAccess=main
ExecStart=\"/home/ana/.local/share/cmux/current/bin/cmux\" host run --mode user
Restart=always
RestartSec=2
# The session host keeps its terminal hosts across a restart: stop only the
# supervisor process (lane 1 handoff contract).
KillMode=process
TimeoutStopSec=30

[Install]
WantedBy=default.target
"
    );
}

#[test]
fn systemd_system_unit_golden() {
    let l = unix(InstallMode::System, Platform::Linux, "/root");
    assert_eq!(
        systemd_system_unit(&l).unwrap(),
        "# Generated by cmux. Do not edit: `cmux server install --system` rewrites this file.
[Unit]
Description=cmux server
Documentation=https://cmux.com/docs/server
Wants=network-online.target cmux-update.path
After=network-online.target

[Service]
Type=notify
NotifyAccess=main
User=cmux
Group=cmux
ExecStart=\"/opt/cmux/current/bin/cmux\" host run --mode system
Restart=always
RestartSec=2
KillMode=process
TimeoutStopSec=30
StateDirectory=cmux
StateDirectoryMode=0700
RuntimeDirectory=cmux
RuntimeDirectoryMode=0755
RuntimeDirectoryPreserve=yes
ConfigurationDirectory=cmux
UMask=0027

[Install]
WantedBy=multi-user.target
"
    );
    assert_eq!(systemd_user_unit(&l), Err(UnitError::WrongLayout));
}

#[test]
fn main_units_leave_terminals_usable() {
    // Hosted terminals need home directories and sudo (server.md 7.4).
    let user = systemd_user_unit(&unix(InstallMode::User, Platform::Linux, "/home/ana")).unwrap();
    let system = systemd_system_unit(&unix(InstallMode::System, Platform::Linux, "/root")).unwrap();
    for unit in [&user, &system] {
        for forbidden in ["ProtectHome", "NoNewPrivileges", "ProtectSystem", "RestrictSUIDSGID"] {
            assert!(!unit.contains(forbidden), "{forbidden}");
        }
    }
}

#[test]
fn update_units_golden() {
    let l = unix(InstallMode::System, Platform::Linux, "/root");
    assert_eq!(
        systemd_update_path_unit(&l).unwrap(),
        "# Generated by cmux. Do not edit: `cmux server install --system` rewrites this file.
[Unit]
Description=Start the cmux updater when the server asks for an update

[Path]
PathExists=/run/cmux/update-request
Unit=cmux-update.service

[Install]
WantedBy=multi-user.target
"
    );
    assert_eq!(
        systemd_update_service_unit(&l).unwrap(),
        "# Generated by cmux. Do not edit: `cmux server install --system` rewrites this file.
[Unit]
Description=cmux store update (root, on request)
Documentation=https://cmux.com/docs/server
ConditionPathExists=/run/cmux/update-request

[Service]
Type=oneshot
ExecStart=\"/opt/cmux/current/bin/cmux\" host update --request /run/cmux/update-request
UMask=0022
NoNewPrivileges=yes
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=strict
ReadWritePaths=/opt/cmux /run/cmux
"
    );
    // The updater runs as root: no User= line.
    assert!(!systemd_update_service_unit(&l).unwrap().contains("User="));
    let user = unix(InstallMode::User, Platform::Linux, "/home/ana");
    assert_eq!(systemd_update_path_unit(&user), Err(UnitError::WrongLayout));
    assert_eq!(systemd_update_service_unit(&user), Err(UnitError::WrongLayout));
}

#[test]
fn app_server_template_is_strict_and_never_boot_started() {
    let l = unix(InstallMode::System, Platform::Linux, "/root");
    let unit = systemd_app_server_template(&l).unwrap();
    for line in [
        "User=app-%i",
        "SupplementaryGroups=cmux-db",
        "ExecStart=\"/opt/cmux/current/bin/cmux\" host app-server %i",
        "MemoryMax=512M",
        "CPUQuota=100%",
        "NoNewPrivileges=yes",
        "PrivateTmp=yes",
        "ProtectHome=yes",
        "ProtectSystem=strict",
        "RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6",
        "ReadWritePaths=/var/lib/cmux/apps/%i /run/cmux/apps/%i",
    ] {
        assert!(unit.lines().any(|l| l == line), "missing {line}");
    }
    assert!(!unit.contains("[Install]"), "only the supervisor starts app servers");
    assert_eq!(
        systemd_app_server_template(&unix(InstallMode::User, Platform::Linux, "/home/ana")),
        Err(UnitError::WrongLayout)
    );
}

#[test]
fn systemd_refuses_unsafe_exec_path() {
    let l = unix(InstallMode::User, Platform::Linux, "/home/a$b");
    assert_eq!(systemd_user_unit(&l), Err(UnitError::UnsafePath("current_cmux")));
}

#[test]
fn launch_agent_plist_golden() {
    let l = unix(InstallMode::User, Platform::MacOs, "/Users/ana");
    assert_eq!(
        launch_agent_plist(&l).unwrap(),
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
\t<key>KeepAlive</key>
\t<dict>
\t\t<key>SuccessfulExit</key>
\t\t<false/>
\t</dict>
\t<key>Label</key>
\t<string>com.cmux.server</string>
\t<key>ProcessType</key>
\t<string>Standard</string>
\t<key>ProgramArguments</key>
\t<array>
\t\t<string>/Users/ana/Library/Application Support/cmux/current/bin/cmux</string>
\t\t<string>host</string>
\t\t<string>run</string>
\t\t<string>--mode</string>
\t\t<string>user</string>
\t</array>
\t<key>RunAtLoad</key>
\t<true/>
\t<key>StandardErrorPath</key>
\t<string>/Users/ana/Library/Application Support/cmux/server/logs/server.log</string>
\t<key>StandardOutPath</key>
\t<string>/Users/ana/Library/Application Support/cmux/server/logs/server.log</string>
\t<key>ThrottleInterval</key>
\t<integer>10</integer>
</dict>
</plist>
"
    );
}

fn app_layout() -> Layout {
    let env = LayoutEnv {
        home: Some("/Users/ana".to_owned()),
        uid: Some(501),
        mac_app_bundle: Some("/Applications/cmux.app".to_owned()),
        ..LayoutEnv::default()
    };
    layout(InstallMode::User, Platform::MacOs, &env).unwrap()
}

/// One golden, two writers: scripts/cmux-next/bundle-server-helper.sh writes
/// the same bytes with plutil for this bundle id
/// (scripts/cmux-next/tests/bundle-server-helper.test.sh compares them).
#[test]
fn app_service_agent_plist_matches_the_bundled_golden() {
    assert_eq!(
        app_service_agent_plist(&app_layout(), "com.cmuxterm.app.debug.testtag").unwrap(),
        include_str!("fixtures/app-service-agent.plist")
    );
}

#[test]
fn app_service_agent_plist_needs_the_app_layout_and_a_plain_bundle_id() {
    let app = app_layout();
    // The app plist carries a per-build label, so the label-less renderer
    // refuses the app layout.
    assert_eq!(launch_agent_plist(&app), Err(UnitError::WrongLayout));
    for bad in ["", ".cmux", "cmux.", "com.cmux app", "com.cmux</string>", "com.cmux\n"] {
        assert_eq!(app_service_agent_plist(&app, bad), Err(UnitError::BadBundleId), "{bad:?}");
    }
    let headless = unix(InstallMode::User, Platform::MacOs, "/Users/ana");
    assert_eq!(app_service_agent_plist(&headless, "com.cmuxterm.app"), Err(UnitError::WrongLayout));
}

#[test]
fn host_run_argv_with_mode_appends_the_mode() {
    assert_eq!(
        host_run_argv_with_mode("/x/cmux", InstallMode::User),
        ["/x/cmux", "host", "run", "--mode", "user"]
    );
    assert_eq!(
        host_run_argv_with_mode("Contents/Resources/bin/cmux", InstallMode::System),
        ["Contents/Resources/bin/cmux", "host", "run", "--mode", "system"]
    );
}

#[test]
fn launchd_plists_carry_the_mode_as_an_argument() {
    // launchd passes a plist environment to every child, including the
    // user's shells, so the mode is an argument and no plist has one.
    let user = unix(InstallMode::User, Platform::MacOs, "/Users/ana");
    let system = unix(InstallMode::System, Platform::MacOs, "/var/root");
    let plists = [
        launch_agent_plist(&user).unwrap(),
        launch_daemon_plist(&user, "ana").unwrap(),
        launch_daemon_plist(&system, "_cmux").unwrap(),
        app_service_agent_plist(&app_layout(), "com.cmuxterm.app.nightly").unwrap(),
    ];
    for plist in &plists {
        assert!(!plist.contains("EnvironmentVariables"), "{plist}");
        assert!(!plist.contains("CMUX_SERVER_MODE"), "{plist}");
    }
    let mode = |p: &str| -> String {
        let tail = &p[p.find("<string>--mode</string>\n").expect("--mode")..];
        tail.lines().nth(1).unwrap().trim().to_owned()
    };
    assert_eq!(mode(&plists[0]), "<string>user</string>");
    assert_eq!(mode(&plists[1]), "<string>user</string>");
    assert_eq!(mode(&plists[2]), "<string>system</string>");
    assert_eq!(mode(&plists[3]), "<string>user</string>");
}

#[test]
fn launch_daemon_and_escaping() {
    let l = unix(InstallMode::User, Platform::MacOs, "/Users/a&b");
    let daemon = launch_daemon_plist(&l, "ana").unwrap();
    assert!(daemon.contains("\t<key>UserName</key>\n\t<string>ana</string>\n"));
    assert!(daemon.contains(
        "<string>/Users/a&amp;b/Library/Application Support/cmux/current/bin/cmux</string>"
    ));
    assert_eq!(launch_daemon_plist(&l, "ana</string>"), Err(UnitError::BadUser));

    let system = unix(InstallMode::System, Platform::MacOs, "/var/root");
    assert_eq!(launch_agent_plist(&system), Err(UnitError::WrongLayout));
    assert!(
        launch_daemon_plist(&system, "_cmux")
            .unwrap()
            .contains("<string>/Library/Application Support/cmux/current/bin/cmux</string>")
    );
}

#[test]
fn windows_service_argv_golden() {
    let l = win(InstallMode::System);
    assert_eq!(
        windows_service_create_argv(&l).unwrap(),
        [
            "sc.exe",
            "create",
            "cmux-server",
            "binPath=",
            r#""C:\Program Files\cmux\current\bin\cmux.exe" host run --mode system"#,
            "start=",
            "auto",
            "obj=",
            r"NT SERVICE\cmux-server",
            "DisplayName=",
            "cmux server",
        ]
    );
    assert_eq!(
        windows_service_failure_argv(),
        [
            "sc.exe",
            "failure",
            "cmux-server",
            "reset=",
            "86400",
            "actions=",
            "restart/2000/restart/2000/restart/60000"
        ]
    );
    assert_eq!(windows_service_create_argv(&win(InstallMode::User)), Err(UnitError::WrongLayout));
}

#[test]
fn scheduled_task_xml_golden_parts() {
    let l = win(InstallMode::User);
    let xml = scheduled_task_xml(&l, r"DESKTOP-1\ana").unwrap();
    assert!(xml.starts_with("<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n<Task version=\"1.4\""));
    assert!(xml.contains("    <LogonTrigger>\n      <Enabled>true</Enabled>\n      <UserId>DESKTOP-1\\ana</UserId>\n    </LogonTrigger>\n"));
    assert!(xml.contains("      <RunLevel>LeastPrivilege</RunLevel>\n"));
    assert!(xml.contains("    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"));
    assert!(xml.contains("    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\n"));
    assert!(xml.contains(
        "      <Command>C:\\Users\\ana\\AppData\\Local\\cmux\\current\\bin\\cmux.exe</Command>\n      <Arguments>host run --mode user</Arguments>\n"
    ));
    assert_eq!(scheduled_task_xml(&l, "ana<x>"), Err(UnitError::BadUser));
    assert_eq!(scheduled_task_xml(&l, r"\ana"), Err(UnitError::BadUser));
    assert_eq!(scheduled_task_xml(&win(InstallMode::System), "ana"), Err(UnitError::WrongLayout));
}
