import Foundation
import Testing
@testable import CmuxNextDaemon

/// The app's daemon capability lists and their checked-in export,
/// `plans/cmux-next/daemon-capabilities.json`, which
/// scripts/cmux-next/check-daemon-capabilities.sh compares with what the
/// bundled cmux-tui serves.
/// `CMUX_UPDATE_DAEMON_CAPABILITIES=1 swift test --filter DaemonCapabilityExportTests` rewrites it.
struct DaemonCapabilityExportTests {
    private let capabilities = DaemonCapabilities.shared

    /// Entries in `unservedByBundledDaemon` on 2026-10-02. The list only
    /// shrinks: a new feature lands with its daemon half and goes in `optional`.
    private static let unservedCeiling: Set<String> = ["remote-terminal-tabs-v1", "detached-terminals-v1"]

    /// Every capability string `DaemonCapabilities` names is in exactly one
    /// list, so the check cannot miss a capability the app references.
    @Test func everyNamedCapabilityIsListed() {
        let named = Mirror(reflecting: capabilities).children.compactMap { $0.value as? String }
        let listed = capabilities.required + capabilities.optional + capabilities.unservedByBundledDaemon
        #expect(Set(listed).count == listed.count, "a capability is in two lists or twice in one")
        let unlisted = Set(named).subtracting(listed)
        #expect(unlisted.isEmpty, "not in required, optional or unservedByBundledDaemon: \(unlisted.sorted())")
        #expect(named.count >= 30, "Mirror found the stored capability constants")
    }

    @Test func unservedListOnlyShrinks() {
        let added = Set(capabilities.unservedByBundledDaemon).subtracting(Self.unservedCeiling)
        #expect(added.isEmpty, "new unserved capabilities \(added.sorted()): land the daemon half on this branch and list them in optional")
    }

    @Test func exportIsFresh() throws {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            .appendingPathComponent("plans/cmux-next/daemon-capabilities.json")
        let current = try Self.json(capabilities)
        if ProcessInfo.processInfo.environment["CMUX_UPDATE_DAEMON_CAPABILITIES"] == "1" {
            try current.write(to: url, atomically: true, encoding: .utf8)
        }
        let stored = try String(contentsOf: url, encoding: .utf8)
        #expect(stored == current, "daemon-capabilities.json is stale; rerun with CMUX_UPDATE_DAEMON_CAPABILITIES=1")
    }

    static func json(_ capabilities: DaemonCapabilities) throws -> String {
        struct Export: Encodable {
            var comment: String
            var required: [String]
            var optional: [String]
            var unservedByBundledDaemon: [String]
        }
        let export = Export(
            comment: "Generated by DaemonCapabilityExportTests from DaemonCapabilities; read by scripts/cmux-next/check-daemon-capabilities.sh.",
            required: capabilities.required.sorted(),
            optional: capabilities.optional.sorted(),
            unservedByBundledDaemon: capabilities.unservedByBundledDaemon.sorted())
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        return String(decoding: try encoder.encode(export), as: UTF8.self) + "\n"
    }
}
