#!/usr/bin/env python3
# Copyright 2026 Manaflow, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later
"""THIRD_PARTY_LICENSES.linux.md: the notices of the cmux-browser-host Linux release.

  linux_release_notices.py [--check] [--cache DIR] [--out FILE]

The cmux-browser-host-release workflow packs this file as THIRD_PARTY_LICENSES.md
into both release archives (x86_64- and aarch64-unknown-linux-gnu), beside the
repository's LICENSE (GPL-3.0-or-later), and runs --check before it builds, so a
stale file fails the release. Regenerate after a change to cmux-tui/Cargo.lock,
the crate version, the embedded JavaScript rows or a toolchain text:

  python3 cmux-tui/build-support/notices/browser-host/linux_release_notices.py

The file names everything that bin/cmux-browser-host contains:
  - the Rust crates of the closure of cmux-browser-host for both Linux targets
    (rust_notices.py, lock text closure: conservative, may list a crate that the
    binary does not link; first-party crates point at the release tag
    cmux-browser-host-v<crate version>), with every license text,
  - the Rust standard library of the rustc in cmux-tui/rust-toolchain.toml
    (toolchains.json),
  - Zig's compiler_rt (and libunwind): cargo-zigbuild links with Zig, whose
    compiler_rt provides the math helpers that QuickJS-ng uses (ceil, floor,
    fmod, trunc, ...; the binary does not import them from glibc). Those math
    files are ported from musl, so musl's COPYRIGHT is printed too
    (cmux-tui/dist/notices/package-notices.json, as for the Windows notices),
  - the third-party JavaScript that the crate embeds (browser-host-js.json, the
    texts that browser_host_js_notices.py checks),
  - glibc, which the binary links dynamically (no glibc code is copied in
    apart from the start files and libc_nonshared, which carry the LGPL
    linking exception).

Crate sources come from fetch_crates.py's CARGO_HOME-shaped cache
(CMUX_NOTICES_CACHE, default ~/.cache/cmux-notices; network on first use, no
cargo). Python 3.11+ standard library only.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import tomllib
from typing import Callable

HERE = Path(__file__).resolve().parent
NOTICES = HERE.parent
ROOT = HERE.parents[3]
OUT = HERE / "THIRD_PARTY_LICENSES.linux.md"
CRATE = ROOT / "cmux-tui/crates/cmux-browser-host"
PACKAGE_NOTICES = ROOT / "cmux-tui/dist/notices"
TARGETS = ("x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu")

sys.path.insert(0, str(HERE))
sys.path.insert(0, str(NOTICES / "toolchains"))
import browser_host_js_notices as js_notices  # noqa: E402
import toolchain_notices  # noqa: E402


class NoticeError(RuntimeError):
    pass


def crate_version() -> str:
    return tomllib.loads((CRATE / "Cargo.toml").read_text(encoding="utf-8"))["package"]["version"]


def source_tag() -> str:
    return f"cmux-browser-host-v{crate_version()}"


def load_inputs() -> dict:
    channel = re.search(r'^\s*channel\s*=\s*"([^"]+)"', (ROOT / "cmux-tui/rust-toolchain.toml").read_text(), re.M)
    toolchains = toolchain_notices.load()
    rust = next((r for r in toolchains.rust if channel and r.version == channel.group(1)), None)
    if rust is None:
        raise NoticeError("toolchains.json has no text for the rustc of cmux-tui/rust-toolchain.toml")
    [zig] = toolchains.zig
    musl = json.loads((PACKAGE_NOTICES / "package-notices.json").read_text(encoding="utf-8"))["musl"]
    return {"rust": rust, "zig": zig, "musl": musl, "js": js_notices.load()}


def _read(path: Path, sha256: str, label: str) -> str:
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() != sha256:
        raise NoticeError(f"{label}: {path} does not match its sha256")
    return data.decode("utf-8")


def _block(title: str, text: str, lang: str = "text") -> str:
    longest = max((len(m) for m in re.findall(r"`+", text)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"#### {title}\n\n{fence}{lang}\n{text.rstrip(chr(10))}\n{fence}\n\n"


def compose(crates_markdown: str, inputs: dict) -> str:
    rust, zig, musl, js = inputs["rust"], inputs["zig"], inputs["musl"], inputs["js"]
    out = [
        f"# Third-party notices: bin/cmux-browser-host {crate_version()} ({', '.join(TARGETS)})\n\n",
        "<!-- Generated by cmux-tui/build-support/notices/browser-host/linux_release_notices.py; do not edit. -->\n\n",
        "bin/cmux-browser-host is cmux, licensed under GPL-3.0-or-later (LICENSE in this archive). "
        f"Its source is https://github.com/manaflow-ai/cmux/tree/{source_tag()}/cmux-tui/crates/cmux-browser-host. "
        "The binary contains the third-party code below.\n\n",
        f"## Rust standard library (rustc {rust.version})\n\n",
        "std, core, alloc, compiler_builtins and the crates they vendor, as the Rust project lists them in "
        f"COPYRIGHT-library.html of rustc {rust.version} ({rust.source}):\n\n",
        _block(f"COPYRIGHT-library.html (rustc {rust.version})", _read(rust.path, rust.sha256, "rust"), "html"),
        f"## Zig {zig.version} compiler_rt and libunwind\n\n",
        "The binary is linked with Zig (cargo-zigbuild, glibc floor 2.31). Zig links its compiler_rt into the "
        "binary; compiler_rt provides math functions that the binary does not import from glibc (ceil, floor, "
        f"fmod, trunc and others, which the QuickJS-ng engine calls). compiler_rt is under Zig's MIT License (Expat; {zig.source}):\n\n",
        _block(f"Zig {zig.version} LICENSE", _read(zig.path, zig.sha256, "zig")),
        "Several compiler_rt math files say 'Ported from musl', which is licensed under the MIT license:\n\n",
        _block(f"musl {musl['version']} COPYRIGHT", _read(PACKAGE_NOTICES / musl["file"], musl["sha256"], "musl")),
        "Zig also links LLVM libunwind into the binary (Apache-2.0 WITH LLVM-exception; the exception needs no "
        "notice for code embedded in object form).\n\n",
        "## glibc\n\n",
        "The binary links the GNU C Library dynamically (libc.so.6, libm.so.6; glibc 2.31 or later). The small "
        "glibc start files and libc_nonshared code that the link adds are under the GNU Lesser General Public "
        "License 2.1 or later with the exception that gives unlimited permission to link the compiled files into "
        "other programs.\n\n",
        f"## Embedded JavaScript ({js['crate']}/js)\n\n",
        "bin/cmux-browser-host embeds its runtime JavaScript (every file of js/manifest.json). These files are "
        "third-party code; the rest is cmux's own code (GPL-3.0-or-later, LICENSE):\n\n",
    ]
    for path, row in sorted(js["files"].items()):
        out.append(f"- `{path}`: {row['owner']} ({row['license']})\n")
    out.append("\n")
    for name in sorted({name for row in js["files"].values() for name in row["texts"]}):
        out.append(_block(f"{name} ({js['texts'][name]['source']})", js_notices.text(js, name)))
    out.append(crates_markdown.rstrip("\n") + "\n")
    return "".join(out)


def crates_markdown(cache: Path, tag: str) -> str:
    fetch = subprocess.run(
        [sys.executable, str(NOTICES / "fetch_crates.py"), "--cache", str(cache), "--lock", str(ROOT / "cmux-tui/Cargo.lock")],
        capture_output=True, text=True,
    )
    if fetch.returncode != 0:
        raise NoticeError(f"fetch_crates.py failed:\n{fetch.stderr}")
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "crates.md"
        command = [
            sys.executable, str(NOTICES / "rust_notices.py"),
            "--lock", str(ROOT / "cmux-tui/Cargo.lock"), "--lock-label", "cmux-tui/Cargo.lock",
            "--root", "cmux-browser-host",
            "--workspace", str(ROOT / "cmux-tui"), "--repo-root", str(ROOT),
            "--first-party", "cmux-tui/crates/*", "--first-party", "cmux-tui/bindings/*",
            "--first-party-license", str(ROOT / "cmux-tui/dist/npm/cmux/LICENSE"),
            "--reviewed", str(NOTICES / "reviewed.json"),
            "--source-tag", tag,
            "--format", "markdown", "--section-id", "rust-crates",
            "--title", f"Rust crates ({', '.join(TARGETS)})",
            "--out", str(out),
        ]
        for target in TARGETS:
            command += ["--target", target]
        result = subprocess.run(command, env={**os.environ, "CARGO_HOME": str(cache)}, capture_output=True, text=True)
        if result.returncode != 0:
            raise NoticeError(f"rust_notices.py failed:\n{result.stderr}")
        return out.read_text(encoding="utf-8")


def main(argv: list[str] | None = None, crates: Callable[[Path, str], str] = crates_markdown) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail when --out differs from a fresh run")
    parser.add_argument("--cache", type=Path, default=Path(os.environ.get("CMUX_NOTICES_CACHE", Path.home() / ".cache/cmux-notices")))
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args(argv)
    try:
        args.cache.mkdir(parents=True, exist_ok=True)
        text = compose(crates(args.cache, source_tag()), load_inputs())
    except (NoticeError, OSError, KeyError, ValueError) as error:
        print(f"linux_release_notices: error: {error}", file=sys.stderr)
        return 1
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.is_file() else None
        if current != text:
            print(
                f"linux_release_notices: error: {args.out} is stale; run "
                "python3 cmux-tui/build-support/notices/browser-host/linux_release_notices.py and commit it",
                file=sys.stderr,
            )
            return 1
        print(f"linux_release_notices: {args.out.name} is current")
        return 0
    args.out.write_text(text, encoding="utf-8")
    print(f"linux_release_notices: wrote {args.out} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
