#!/usr/bin/env python3
"""Write or check Packages/macOS/CmuxNext/ci-target-graph.json.

The graph is what scripts/ci/cmux_next_route.py reads to pick the CmuxNext test
targets a pull request can affect. It comes from SwiftPM, not from reading
Package.swift by eye:

  targets   `swift package dump-package`: each target's kind, source
            directory, the targets it depends on in this package and the local
            packages whose products it uses
  packages  each local package dependency's repository directory
  reads     for each test target, the repository files and directories its
            sources name in string literals (schemas, fixtures, plans, cmux-tui
            vectors), which a test can read without depending on them in SwiftPM

`dump-package` needs the Swift 6.2 tools, so this runs on a Mac (the
`cmux-next generated files` job); `--check` fails when the committed file is
stale, and that job uploads the regenerated file as an artifact.

Usage: scripts/cmux-next/ci-target-graph.py [--check] [--dump FILE]
  --dump FILE  read dump-package JSON from FILE instead of running swift
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PACKAGE = ROOT / "Packages/macOS/CmuxNext"
GRAPH = PACKAGE / "ci-target-graph.json"
HEADER = "Generated by scripts/cmux-next/ci-target-graph.py from swift package dump-package; do not edit."

STRING_LITERAL = re.compile(r'"((?:[^"\\\n]|\\.)*)"')
# Literals that name the machine, not the checkout.
SYSTEM_PREFIXES = ("/", "~")


def repo_relative(path: Path) -> str | None:
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return None


def dump_package(dump: Path | None) -> dict:
    if dump is not None:
        return json.loads(dump.read_text(encoding="utf-8"))
    output = subprocess.run(
        ["swift", "package", "dump-package"], cwd=PACKAGE, check=True, capture_output=True, text=True
    ).stdout
    return json.loads(output)


def local_packages(manifest: dict) -> dict[str, str]:
    """Local package name and identity (lowercased) -> repository directory."""
    found: dict[str, str] = {}
    for dependency in manifest.get("dependencies", []):
        for spec in dependency.get("fileSystem", []):
            path = Path(spec["path"])
            if not path.is_absolute():
                path = PACKAGE / path
            relative = repo_relative(path)
            if relative is None:
                continue
            found[path.name] = relative
    return found


def dependency_name(dependency: dict) -> tuple[str, str]:
    """('target', name) or ('product', package) for one dump-package dependency."""
    if "target" in dependency:
        return "target", dependency["target"][0]
    if "product" in dependency:
        product = dependency["product"]
        return "product", product[1] or product[0]
    if "byName" in dependency:
        return "byName", dependency["byName"][0]
    raise SystemExit(f"unknown dependency shape: {dependency}")


def literal_reads(source_dir: Path) -> list[str]:
    """Repository paths a test target's sources name in string literals."""
    reads: set[str] = set()
    for source in sorted(source_dir.rglob("*.swift")):
        text = source.read_text(encoding="utf-8")
        for literal in STRING_LITERAL.findall(text):
            # An interpolated path counts up to its first interpolation.
            literal = literal.split("\\(", 1)[0]
            # Two path segments at least: a lone "docs/" is a folder name in a
            # fixture far more often than a read of the repository's docs.
            if "/" not in literal.strip("/") or literal.startswith(SYSTEM_PREFIXES) or "://" in literal:
                continue
            if any(ch.isspace() for ch in literal):
                continue
            for base in (ROOT, PACKAGE, source_dir, source.parent):
                candidate = base / literal
                try:
                    if not candidate.exists():
                        continue
                except OSError:
                    # Not a path at all: a certificate or other blob too long
                    # for the filesystem (ENAMETOOLONG on macOS).
                    continue
                relative = repo_relative(candidate)
                if relative is None or relative in ("", "."):
                    continue
                # Reads inside the target itself are already its sources.
                if (relative + "/").startswith(repo_relative(source_dir) + "/"):
                    continue
                if candidate.is_dir():
                    relative += "/"
                reads.add(relative)
                break
    # A file under a directory that is itself read adds nothing.
    return sorted(
        read for read in reads
        if not any(other != read and other.endswith("/") and read.startswith(other) for other in reads)
    )


def build_graph(manifest: dict) -> dict:
    packages = local_packages(manifest)
    names = {target["name"] for target in manifest["targets"]}
    package_root = repo_relative(PACKAGE)
    targets: dict[str, dict] = {}
    for target in sorted(manifest["targets"], key=lambda t: t["name"]):
        kind = target["type"]
        default = ("Tests/" if kind == "test" else "Sources/") + target["name"]
        path = target.get("path") or (default if kind != "binary" else None)
        local_targets: set[str] = set()
        used_packages: set[str] = set()
        for dependency in target.get("dependencies", []):
            how, name = dependency_name(dependency)
            if how in ("target", "byName") and name in names:
                local_targets.add(name)
            elif name in packages:
                used_packages.add(name)
            elif how == "product":
                # A remote package (Sparkle): its pin is Package.resolved.
                continue
            else:
                raise SystemExit(f"{target['name']}: dependency {name} is neither a target nor a local package")
        entry: dict = {
            "kind": kind,
            "path": f"{package_root}/{path}" if path else None,
            "targets": sorted(local_targets),
            "packages": sorted(used_packages),
        }
        if kind == "test":
            entry["reads"] = literal_reads(PACKAGE / path)
        targets[target["name"]] = entry
    return {
        "_comment": HEADER,
        "packages": dict(sorted(packages.items())),
        "targets": targets,
    }


def render(graph: dict) -> str:
    return json.dumps(graph, indent=2, sort_keys=False) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when the committed graph is stale")
    parser.add_argument("--dump", type=Path, help="dump-package JSON to read instead of running swift")
    args = parser.parse_args(argv)

    text = render(build_graph(dump_package(args.dump)))
    if args.check:
        current = GRAPH.read_text(encoding="utf-8") if GRAPH.exists() else ""
        if current != text:
            print(f"{GRAPH.relative_to(ROOT)} is stale. Run: scripts/cmux-next/ci-target-graph.py", file=sys.stderr)
            return 1
        print(f"{GRAPH.relative_to(ROOT)} is fresh")
        return 0
    GRAPH.write_text(text, encoding="utf-8")
    print(f"wrote {GRAPH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
