// Why no right-click menu offers an action (plans/cmux-next/actions.md);
// the other surfaces' decisions are in ActionSurfaceCatalog+Exemptions.swift.

nonisolated extension ActionSurfaceCatalog {
    /// Why no right-click menu offers an action.
    static let contextMenuExemption: [ActionID: SurfaceExemption] = byReason(contextMenuExemptionsByReason)
    static let contextMenuExemptionsByReason: [SurfaceExemption: [ActionID]] = [
        // The menus offer New Tab Page, whose field is this action's GUI form.
        .duplicateOfDefault: [
            "newTab.submit",
        ],
        .secondaryEngine: [
            "openBrowser.webkit",
            "browser.openInWebKit",
        ],
        .unimplemented: [
            "palette.browserToggleOmnibar",
            "toggleReactGrab",
            "palette.openCloudPane",
            "palette.openVaultPane",
            "palette.openFindPane",
            "palette.openFilesPane",
        ],
        .noObject: [
            "sidebar.profileMenu", "browser.downloads.showFolder",
            "home.show",
            "openSettings", "appearance.customize", "newWindow", "newIncognitoWindow", "closeWindow", "minimizeWindow", "toggleFullScreen",
            "closeAllWindows", "zoomWindow", "selectNextWindow", "selectPreviousWindow",
            "quit", "quitKeepSessions", "quitEndSessions", "quitEndEverything", "globalSearch", "commandPalette",
            "palette.openTaskManager", "palette.sleepyMode", "keepMacAwake", "about", "manageLayouts",
            "palette.findWork", "reopenClosedBrowserPanel", "palette.browserClearHistory", "importFromBrowser", "password.importCSV", "browser.allowAgentWithExtensions",
            "palette.enableBrowser", "palette.disableBrowser", "toggleRightSidebar", "switchRightSidebarToFiles",
            "switchRightSidebarToFind", "switchRightSidebarToSessions", "switchRightSidebarToFeed",
            "switchRightSidebarToDock", "switchRightSidebarToMachines", "palette.toggleMatchTerminalBackground",
            "palette.enableMinimalMode", "palette.disableMinimalMode", "showNotifications", "feed.show", "markAllNotificationsRead",
            "clearAllNotifications", "notifications.toggleBanners", "notifications.dismissal.keystroke",
            "notifications.dismissal.focus", "notifications.dismissal.click", "notifications.dismissal.explicit",
            "notifications.dismissal.timeout", "notifications.dismissal.never", "palette.openTerminalChatView",
            "palette.quickAgentChat",
            "palette.launchClaudeTeams", "palette.launchCodexTeams", "palette.computerUse.setup",
            "palette.computerUse.accessibility", "palette.computerUse.screenRecording", "computerUseStop",
            "newCloudMachine", "cloudDiagnostics", "openTeamPicker", "palette.auth.signIn", "palette.auth.signOut",
            "palette.mobileConnect", "accounts.show", "accounts.refresh", "accounts.reauthenticate",
            "accounts.connect", "accounts.remove", "reloadConfiguration", "palette.openCmuxSettingsFile",
            "palette.openGhosttySettings", "ghostty.showDiagnostics", "palette.makeDefaultBrowser", "palette.makeDefaultTerminal",
            "palette.toggleSetting", "palette.shortcutKeymap", "palette.searchShortcuts", "palette.installCLI",
            "palette.uninstallCLI", "palette.restartSocketListener", "palette.checkForUpdates", "updates.whatsNew", "announcements.show", "announcements.hide",
            "palette.applyUpdateIfAvailable", "palette.switchAppChannel", "palette.pro.upgrade",
            "palette.welcomeChecklist", "onboarding.continueSetup", "palette.importClassicSessions", "sendFeedback", "help.featureFlags", "help.documentation", "help.showCrashLogs",
            "appearance.density.compact", "appearance.density.comfortable", "appearance.animationSpeed.fast",
            "appearance.animationSpeed.normal", "appearance.animationSpeed.off", "browser.defaultEngine.chromium",
            "browser.defaultEngine.webkit", "appearance.paneBorder.toggle", "appearance.panePadding.toggle",
            "appearance.paneCorners.toggle", "layout.centerFocusedColumn.never", "layout.centerFocusedColumn.always",
            "layout.centerFocusedColumn.onOverflow", "focusRing.toggle", "focusRing.style.ring",
            "focusRing.style.glow", "focusRing.singlePane.toggle", "appearance.paneBorderWidth.toggle",
            "appearance.paneBorderColor.reset", "appearance.titlebar.minimal", "appearance.titlebar.standard",
            "browser.hibernation.off", "browser.hibernation.moderate", "browser.hibernation.aggressive",
            "layout.toggleStripScrollbar", "recentlyFocused", "recentlyClosed", "history.commands", "history.show",
            "browserShowHistory", "history.search", "history.resumeAgentSession", "history.reopen", "history.open", "history.clear",
            "layout.undo", "bookmark.add", "bookmark.import", "bookmark.importFromBrowser", "bookmark.export", "agentActivity.open",
        ],
        .noTargetSurface: [
            "browserProfile.openLink", "file.open",
            "openLinkInDefaultBrowser",
            "tabGroup.deleteSaved",
            "tabGroup.reopenSaved",
            "taskManager.killProcess", "toggleChecklistItemComplete", "canvasOverview", "canvasTidy",
            "canvasAlignLeft", "canvasAlignRight", "canvasAlignTop", "canvasAlignBottom", "canvasEqualizeWidths",
            "canvasEqualizeHeights", "canvasDistributeHorizontally", "canvasDistributeVertically", "simulatorHome",
            "simulatorRotateLeft", "simulatorRotateRight", "simulatorToggleAppearance",
            "simulatorToggleSoftwareKeyboard", "agentPane.searchChats", "screenGroup.reopenSaved", "screenGroup.deleteSaved",
            "resumeCommandSet", "resumeCommandEdit", "resumeCommandClear", "saveFilePreview", "markdownSave",
            "markdownLink", "markdownBack", "markdownForward",
            "toggleFileEditorWordWrap", "filePreviewOpenWith", "filePreviewOpenExternally",
            "filePreviewRevealInFinder", "diffViewerNextLine", "diffViewerPreviousLine", "diffViewerHalfPageDown",
            "diffViewerHalfPageUp", "diffViewerNextHunk", "diffViewerPreviousHunk", "diffViewerGoToBottom",
            "diffViewerGoToTop", "diffViewerSearch", "diffViewerNextFile", "diffViewerPreviousFile", "fileEditorGotoLine", "fileEditorReplace", "fileEditorAction",
            "palette.vscodeServeWebStop", "palette.vscodeServeWebRestart", "fileExplorerOpenSelection",
            "fileExplorerOpenSelectionFinderAlias", "fileExplorerOpenInCmux", "fileExplorerReveal",
            "fileExplorerCopyPath", "fileExplorerCopyRelativePath", "fileExplorerOpenWith", "vaultOpenSession",
            "vaultResumeInNewWorkspace", "vaultCopyResumeCommand", "vaultOpenPullRequest", "checklistEditItem",
            "checklistMarkInProgress", "checklistCompleteItem", "checklistRemoveItem", "checklistOpenAsPane",
            "checklistAttachImages", "cloudExec", "cloudDomainList", "cloudPublicationList",
        ],
        .focusMove: [
            "history.goTo",
            "showHideAllWindows", "goToWorkspace", "showMainWindow", "tab.focus", "pane.focus", "screen.focus", "nextSidebarTab", "prevSidebarTab",
            "nextSidebarTabInGroup", "prevSidebarTabInGroup", "nextWorkspaceGroup", "prevWorkspaceGroup",
            "selectWorkspaceByNumber", "workspace.selectFirst",
            "workspace.selectLast", "workspace.selectLastUsed", "space.next", "space.previous", "space.selectByNumber",
            "space.switch", "focusLeft", "focusRight", "focusUp", "focusDown", "focusPreviousPane", "focusNextPane",
            "canvasRevealFocusedPane", "nextSurface", "prevSurface", "selectSurfaceByNumber",
            "screen.next", "screen.previous", "screen.select", "screen.selectLast", "focusTextBoxInput",
            "focusBrowserAddressBar", "focusLocation", "focusRightSidebar", "vaultFocusSession", "jumpToUnread",
            "markOldestUnreadAndJumpNext", "computerUseFocus", "computerUseFocusCallingTerminal", "column.focusLeft",
            "column.focusRight", "focusHistoryBack", "focusHistoryForward", "focusHistoryLast",
        ],
        .stepAdjust: [
            "resizePaneLeft", "resizePaneRight", "resizePaneUp", "resizePaneDown", "increaseWorkspaceTerminalFontSize",
            "decreaseWorkspaceTerminalFontSize", "resetWorkspaceTerminalFontSize", "canvasZoomIn", "canvasZoomOut",
            "canvasZoomReset", "browserZoomIn", "browserZoomOut", "browserZoomReset", "markdownZoomIn",
            "markdownZoomOut", "markdownZoomReset", "fileEditorZoomIn", "fileEditorZoomOut", "fileEditorZoomReset", "appearance.interfaceSize.increase",
            "appearance.interfaceSize.decrease", "appearance.interfaceSize.reset", "appearance.uiScale.increase", "appearance.uiScale.decrease", "appearance.uiScale.reset", "column.cycleWidth",
            "column.cycleWidthBack", "terminal.increaseFontSize", "terminal.decreaseFontSize",
            "terminal.resetFontSize", "terminal.scrollPageUp", "terminal.scrollPageDown", "terminal.scrollToTop",
            "terminal.scrollToBottom",
        ],
        .familyMember: [
            "cycleWorkspaceStatus", "workspaceGroup.collapse", "workspaceGroup.expand", "openBrowser",
            "tabGroup.collapse", "tabGroup.expand", "screenGroup.collapse", "screenGroup.expand",
            "browser.extension.run", "browser.extension.options", "browser.extension.pin", "browser.extension.unpin",
            "browser.extension.enable", "browser.extension.disable", "browser.extension.reload",
            "browser.extension.remove", "browser.extension.command", "palette.attemptUpdate",
        ],
        .liveInput: [
            "browserLinkHints", "browserLinkHintsNewSplit",
            "palette.toggleDictation",
            "toggleTerminalCopyMode", "palette.terminalToggleTextBoxInput", "cycleTextBoxSubmitAction",
            "attachTextBoxFile", "sendCtrlFToTerminal", "pasteLastScreenshot", "find", "findInDirectory", "findNext",
            "findPrevious", "hideFind", "toggleUnread", "terminal.scrollToSelection",
        ],
        .dragGesture: [
            "space.move", "browser.extension.move", "bookmark.move", "space.moveLeft", "space.moveRight",
        ],
        .minimalMenu: [
            "space.newWindow", "space.newWorkspace", "space.clearIcon", "space.setDefaults", "browserProfile.clearSpaceDefault",
        ],
        .paletteInternal: [
            "commandPaletteNext", "commandPalettePrevious",
        ],
        .devOnly: [
            "openDebugSettings", "palette.onboardingGallery",
        ],
    ]
}
