// Right-click placements, screens to bookmarks (see ActionSurfaceCatalog+Menus.swift).

nonisolated extension ActionSurfaceCatalog {
    static let contentPlacements: [ActionID: [ContextMenuPlacement]] = [
        "screen.new": [p(.screen, .create, 0), p(.screenBar, .create, 0)],
        "screen.newWith": [p(.screenBar, .create, 1), p(.screen, .create, 2, folder: .new)],
        "screen.duplicate": [p(.screen, .create, 1, folder: .new)],
        "screen.close": [p(.screen, .close, 400)],
        "screen.closeOthers": [p(.screen, .close, 401, folder: .close)],
        "screen.closeToRight": [p(.screen, .close, 402, folder: .close)],
        "screen.closeToLeft": [p(.screen, .close, 403, folder: .close)],
        "screen.reopenClosed": [p(.screenBar, .create, 2)],
        "screen.rename": [p(.screen, .identity, 100)],
        "screen.clearName": [p(.screen, .identity, 100, folder: .options)],
        "screen.setColor": [p(.screen, .identity, 101, .submenu, folder: .appearance)],
        "screen.clearColor": [p(.screen, .identity, 9, in: "screen.setColor")],
        "screen.setIcon": [p(.screen, .identity, 102, folder: .appearance)],
        "screen.clearIcon": [p(.screen, .identity, 103, folder: .appearance)],
        "screen.togglePin": [p(.screen, .identity, 104)],
        "screen.color.grey": [p(.screen, .identity, 0, in: "screen.setColor")],
        "screen.color.blue": [p(.screen, .identity, 1, in: "screen.setColor")],
        "screen.color.red": [p(.screen, .identity, 2, in: "screen.setColor")],
        "screen.color.yellow": [p(.screen, .identity, 3, in: "screen.setColor")],
        "screen.color.green": [p(.screen, .identity, 4, in: "screen.setColor")],
        "screen.color.pink": [p(.screen, .identity, 5, in: "screen.setColor")],
        "screen.color.purple": [p(.screen, .identity, 6, in: "screen.setColor")],
        "screen.color.cyan": [p(.screen, .identity, 7, in: "screen.setColor")],
        "screen.color.orange": [p(.screen, .identity, 8, in: "screen.setColor")],
        "screen.moveLeft": [p(.screen, .move, 300, folder: .move)],
        "screen.moveRight": [p(.screen, .move, 301, folder: .move)],
        "screen.moveToWorkspace": [p(.screen, .move, 302, folder: .move)],
        "screen.moveToNewWorkspace": [p(.screen, .move, 303, folder: .move)],
        "screen.moveToNewWindow": [p(.screen, .move, 304, folder: .move)],
        "screenGroup.create": [p(.screen, .organize, 200, folder: .group)],
        "screenGroup.addScreen": [p(.screen, .organize, 201, folder: .group)],
        "screenGroup.removeScreen": [p(.screen, .organize, 202, folder: .group)],
        "screenGroup.newScreen": [p(.screenGroup, .create, 0)],
        "screenGroup.rename": [p(.screenGroup, .identity, 1)],
        "screenGroup.setColor": [p(.screenGroup, .identity, 2, .submenu, folder: .appearance)],
        "screenGroup.toggleCollapsed": [p(.screenGroup, .organize, 3)],
        "screenGroup.ungroup": [p(.screenGroup, .close, 300)],
        "screenGroup.close": [p(.screenGroup, .close, 301)],
        "screenGroup.moveLeft": [p(.screenGroup, .move, 200, folder: .move)],
        "screenGroup.moveRight": [p(.screenGroup, .move, 201, folder: .move)],
        "screenGroup.moveToWorkspace": [p(.screenGroup, .move, 202, folder: .move)],
        "screenGroup.moveToNewWorkspace": [p(.screenGroup, .move, 203, folder: .move)],
        "screenGroup.moveToNewWindow": [p(.screenGroup, .move, 204, folder: .move)],
        "screenGroup.save": [p(.screenGroup, .organize, 100, folder: .group)],
        "screenGroup.unsave": [p(.screenGroup, .organize, 101, folder: .group)],
        "screenGroup.color.grey": [p(.screenGroup, .identity, 0, in: "screenGroup.setColor")],
        "screenGroup.color.blue": [p(.screenGroup, .identity, 1, in: "screenGroup.setColor")],
        "screenGroup.color.red": [p(.screenGroup, .identity, 2, in: "screenGroup.setColor")],
        "screenGroup.color.yellow": [p(.screenGroup, .identity, 3, in: "screenGroup.setColor")],
        "screenGroup.color.green": [p(.screenGroup, .identity, 4, in: "screenGroup.setColor")],
        "screenGroup.color.pink": [p(.screenGroup, .identity, 5, in: "screenGroup.setColor")],
        "screenGroup.color.purple": [p(.screenGroup, .identity, 6, in: "screenGroup.setColor")],
        "screenGroup.color.cyan": [p(.screenGroup, .identity, 7, in: "screenGroup.setColor")],
        "screenGroup.color.orange": [p(.screenGroup, .identity, 8, in: "screenGroup.setColor")],
        "terminal.keep": [p(.tab, .identity, 210, folder: .options)],
        "clearScreenKeepScrollback": [p(.terminalSelection, .reset, 300, folder: .options)],
        "useSelectionForFind": [p(.terminalSelection, .edit, 3)],
        "terminalCopy": [p(.terminalSelection, .edit, 0)],
        "terminalPaste": [p(.terminalSelection, .edit, 1)],
        "resetTerminal": [p(.terminalSelection, .reset, 301, folder: .options)],
        "reconnectPane": [p(.pane, .connection, 201, folder: .connection)],
        "palette.terminalOpenDirectory": [p(.terminalSelection, .inspect, 0, folder: .tools)],
        "browserBack": [p(.browserPage, .navigate, 0)],
        "browserForward": [p(.browserPage, .navigate, 1)],
        "browserReload": [p(.browserPage, .navigate, 2)],
        "browserHardReload": [p(.browserPage, .navigate, 3)],
        "browser.openInChromium": [p(.tab, .reopen, 100, folder: .openIn)],
        "toggleBrowserDeveloperTools": [p(.browserPage, .inspect, 201)],
        "showBrowserJavaScriptConsole": [p(.browserPage, .inspect, 202, folder: .tools)],
        "inspectBrowserElement": [p(.browserPage, .inspect, 203, folder: .tools)],
        "toggleBrowserFocusMode": [p(.browserPage, .view, 0, folder: .options)],
        "toggleBrowserDesignMode": [p(.browserPage, .view, 1, folder: .options)],
        "splitBrowserRight": [p(.pane, .create, 5, folder: .new)],
        "splitBrowserDown": [p(.pane, .create, 6, folder: .new)],
        "palette.browserOpenDefault": [p(.browserPage, .inspect, 101, folder: .tools)],
        "browserScreenshotPage": [p(.browserPage, .inspect, 102, folder: .tools)],
        "browserScreenshotSection": [p(.browserPage, .inspect, 103, folder: .tools)],
        "browserTheme": [p(.browserPage, .identity, 0, .choices, folder: .appearance)],
        "browser.pageInfo": [p(.browserPage, .inspect, 200, .submenu, folder: .tools), p(.browserPage, .inspect, 0, in: "browser.pageInfo")],
        "browser.pageInfo.connection": [p(.browserPage, .inspect, 1, in: "browser.pageInfo")],
        "browser.pageInfo.certificate": [p(.browserPage, .inspect, 2, in: "browser.pageInfo")],
        "browser.pageInfo.reenableCertificateWarnings": [p(.browserPage, .inspect, 3, in: "browser.pageInfo")],
        "browser.pageInfo.cookies": [p(.browserPage, .inspect, 200, in: "browser.pageInfo")],
        "browser.pageInfo.manageSiteData": [p(.browserPage, .inspect, 201, in: "browser.pageInfo")],
        "browser.pageInfo.deleteSiteData": [p(.browserPage, .inspect, 202, in: "browser.pageInfo")],
        "browser.pageInfo.setPermission": [p(.browserPage, .inspect, 100, in: "browser.pageInfo")],
        "browser.pageInfo.resetPermissions": [p(.browserPage, .inspect, 101, in: "browser.pageInfo")],
        "browser.pageInfo.siteSettings": [p(.browserPage, .inspect, 300, in: "browser.pageInfo")],
        "browser.pageInfo.aboutThisPage": [p(.browserPage, .inspect, 301, in: "browser.pageInfo")],
        "browser.extensions.menu": [p(.browserPage, .inspect, 300, folder: .tools)],
        "browser.extensions.manage": [p(.browserPage, .inspect, 301, folder: .tools)],
        "browser.extensions.webStore": [p(.browserPage, .inspect, 302, folder: .tools)],
        "browser.extensions.loadUnpacked": [p(.browserPage, .inspect, 303, folder: .tools)],
        "browserProfile.new": [p(.browserProfile, .create, 300)],
        "browserProfile.rename": [p(.browserProfile, .identity, 100)],
        "browserProfile.setColor": [p(.browserProfile, .identity, 101)],
        "browserProfile.clearColor": [p(.browserProfile, .identity, 102)],
        "browserProfile.setIcon": [p(.browserProfile, .identity, 103)],
        "browserProfile.clearIcon": [p(.browserProfile, .identity, 104)],
        "browserProfile.delete": [p(.browserProfile, .close, 400)],
        "browserProfile.newTab": [p(.newTab, .create, 3), p(.browserProfile, .create, 0)],
        "browserProfile.newWindow": [p(.browserProfile, .create, 1)],
        "browserProfile.newWorkspace": [p(.browserProfile, .create, 2)],
        "browserProfile.setWorkspaceDefault": [p(.workspaceRow, .identity, 300, folder: .options)],
        "browserProfile.clearWorkspaceDefault": [p(.workspaceRow, .identity, 301, folder: .options)],
        "browserProfile.setSpaceDefault": [p(.profile, .identity, 103, .choices, label: SpaceMenuLabels.setBrowserProfile)],
        "browserProfile.moveTab": [p(.tab, .reopen, 102, folder: .openIn)],
        "browserProfile.duplicateTab": [p(.tab, .reopen, 103, folder: .openIn)],
        "browserProfile.manageExtensions": [p(.browserProfile, .inspect, 200)],
        "toggleSidebar": [p(.sidebarBackground, .view, 300)],
        "notificationOpen": [p(.notification, .navigate, 0)],
        "notificationCopy": [p(.notification, .inspect, 0)],
        "notificationToggleRead": [p(.notification, .identity, 0)],
        "notificationDismiss": [p(.notification, .close, 0)],
        "notifications.toggleWorkspaceMute": [p(.workspaceRow, .identity, 113, folder: .options)],
        "palette.newAgentChat": [p(.newTab, .create, 4)],
        "newTab.page": [p(.newTab, .create, 5)],
        "palette.forkAgentConversationRight": [p(.terminalSelection, .create, 200, folder: .agent)],
        "palette.forkAgentConversationLeft": [p(.terminalSelection, .create, 202, folder: .agent)],
        "palette.forkAgentConversationTop": [p(.terminalSelection, .create, 203, folder: .agent)],
        "palette.forkAgentConversationBottom": [p(.terminalSelection, .create, 204, folder: .agent)],
        "palette.forkAgentConversationNewTab": [p(.terminalSelection, .create, 201, folder: .agent)],
        "palette.forkAgentConversationNewWorkspace": [p(.terminalSelection, .create, 205, folder: .agent)],
        "newCloudWorkspace": [p(.sidebarBackground, .create, 200, folder: .new)],
        "palette.cloud.fork": [p(.cloudMachine, .connection, 203, folder: .connection)],
        "palette.cloud.snapshot": [p(.cloudMachine, .connection, 202, folder: .connection)],
        "palette.cloud.restore": [p(.cloudMachine, .connection, 207, folder: .connection)],
        "palette.cloud.promoteTemplate": [p(.cloudMachine, .connection, 206, folder: .connection)],
        "palette.cloud.status": [p(.cloudMachine, .connection, 201, folder: .connection)],
        "palette.cloud.ports": [p(.cloudMachine, .connection, 205, folder: .connection)],
        "palette.cloud.tools": [p(.cloudMachine, .inspect, 103, folder: .tools)],
        "palette.cloud.handoff": [p(.cloudMachine, .connection, 204, folder: .connection)],
        "cloudFilesList": [p(.cloudMachine, .create, 2, folder: .tools)],
        "cloudFileRead": [p(.cloudMachine, .create, 3, folder: .tools)],
        "cloudFileWrite": [p(.cloudMachine, .create, 4, folder: .tools)],
        "cloudFileMkdir": [p(.cloudMachine, .create, 5, folder: .tools)],
        "cloudFileRemove": [p(.cloudMachine, .create, 6, folder: .tools)],
        "cloudFileStat": [p(.cloudMachine, .create, 7, folder: .tools)],
        "cloudPrepareSCP": [p(.cloudMachine, .create, 8, folder: .tools)],
        "cloudTunnelAttach": [p(.cloudMachine, .create, 9, folder: .tools)],
        "cloudTunnelDetach": [p(.cloudMachine, .create, 10, folder: .tools)],
        "cloudTunnelRotateKey": [p(.cloudMachine, .create, 11, folder: .tools)],
        "cloudNetworkList": [p(.cloudMachine, .create, 12, folder: .tools)],
        "cloudFirewallList": [p(.cloudMachine, .create, 13, folder: .tools)],
        "cloudFirewallGet": [p(.cloudMachine, .create, 14, folder: .tools)],
        "cloudFirewallCreate": [p(.cloudMachine, .create, 15, folder: .tools)],
        "cloudFirewallDelete": [p(.cloudMachine, .create, 16, folder: .tools)],
        "cloudNewTerminal": [p(.cloudMachine, .create, 0)],
        "cloudOpenMachine": [p(.cloudMachine, .create, 1)],
        "cloudSSH": [p(.cloudMachine, .create, 2)],
        "cloudRenameMachine": [p(.cloudMachine, .identity, 2)],
        "cloudKillMachine": [p(.cloudMachine, .close, 300)],
        "cloudPauseMachine": [p(.cloudMachine, .connection, 208, folder: .connection)],
        "cloudResumeMachine": [p(.cloudMachine, .connection, 209, folder: .connection)],
        "cloudCopyLink": [p(.cloudMachine, .inspect, 101, folder: .copy)],
        "cloudCopyPort": [p(.cloudMachine, .inspect, 102, folder: .copy)],
        "cloudCopyMachineID": [p(.cloudMachine, .inspect, 100, folder: .copy)],
        "cloudResizeMachine": [p(.cloudMachine, .connection, 200, folder: .connection)],
        "palette.cloud.deleteSnapshot": [p(.cloudMachine, .close, 301, folder: .connection)],
        "remote.connect": [p(.sidebarBackground, .create, 201, folder: .new)],
        "remote.newWorkspace": [p(.sshMachine, .create, 0)],
        "remote.openTerminalHere": [p(.pane, .create, 7, folder: .new)],
        "remote.reconnect": [p(.sshMachine, .connection, 100)],
        "remote.disconnect": [p(.sshMachine, .connection, 101)],
        "remote.install": [p(.sshMachine, .connection, 102)],
        "remote.forget": [p(.sshMachine, .close, 200)],
        "hibernateTab": [p(.tab, .connection, 0, folder: .options)],
        "wakeTab": [p(.tab, .connection, 1, folder: .options)],
        "tab.moveToNewSplit": [p(.tab, .move, 404, folder: .move)],
        "tab.moveToNewColumn": [p(.tab, .move, 405, folder: .move)],
        "tab.moveToNewDockColumn": [p(.tab, .move, 408, folder: .move)],
        "tab.moveToWorkspace": [p(.tab, .move, 413, folder: .move)],
        "tab.moveToNewWindow": [p(.tab, .move, 407, folder: .move)],
        "tabGroup.moveLeft": [p(.tabGroup, .move, 200, folder: .move)],
        "tabGroup.moveRight": [p(.tabGroup, .move, 201, folder: .move)],
        "splitLeft": [p(.pane, .create, 2, folder: .new), p(.terminalSelection, .create, 102, folder: .split)],
        "splitUp": [p(.pane, .create, 3, folder: .new), p(.terminalSelection, .create, 103, folder: .split)],
        "swapPaneLeft": [p(.pane, .move, 301, folder: .move)],
        "swapPaneRight": [p(.pane, .move, 302, folder: .move)],
        "swapPaneUp": [p(.pane, .move, 303, folder: .move)],
        "swapPaneDown": [p(.pane, .move, 304, folder: .move)],
        "closePane": [p(.pane, .close, 600)],
        "renamePane": [p(.pane, .identity, 103)],
        "column.moveLeft": [p(.pane, .move, 310, folder: .move)],
        "column.moveRight": [p(.pane, .move, 311, folder: .move)],
        "column.center": [p(.pane, .layout, 504, folder: .layout)],
        "column.widthOneThird": [p(.pane, .layout, 500, folder: .layout)],
        "column.widthHalf": [p(.pane, .layout, 501, folder: .layout)],
        "column.widthTwoThirds": [p(.pane, .layout, 502, folder: .layout)],
        "column.widthFull": [p(.pane, .layout, 503, folder: .layout)],
        "column.dock": [p(.pane, .layout, 400, folder: .layout)],
        "column.undock": [p(.pane, .layout, 401, folder: .layout)],
        "column.float": [p(.pane, .layout, 402, folder: .layout)],
        "column.dockLeft": [p(.pane, .layout, 403, folder: .layout)],
        "column.dockRight": [p(.pane, .layout, 404, folder: .layout)],
        "column.dockTop": [p(.pane, .layout, 405, folder: .layout)],
        "column.dockBottom": [p(.pane, .layout, 406, folder: .layout)],
        "terminal.selectAll": [p(.terminalSelection, .edit, 2)],
        "terminal.clear": [p(.terminalSelection, .reset, 302, folder: .options)],
        "terminal.sendText": [p(.terminalSelection, .edit, 4)],
        "bookmark.addPage": [p(.browserPage, .inspect, 100), p(.bookmark, .create, 200), p(.bookmarksBar, .create, 0)],
        "bookmark.addAllTabs": [p(.bookmarksBar, .create, 2), p(.bookmark, .create, 202)],
        "bookmark.newFolder": [p(.bookmark, .create, 201), p(.bookmarksBar, .create, 1)],
        "bookmark.open": [p(.bookmark, .create, 0)],
        "bookmark.openInNewTab": [p(.bookmark, .create, 1)],
        "bookmark.openInBackgroundTab": [p(.bookmark, .create, 2)],
        "bookmark.openAll": [p(.bookmark, .create, 3)],
        "bookmark.edit": [p(.bookmark, .identity, 100)],
        "bookmark.remove": [p(.bookmark, .close, 101)],
        "bookmark.toggleBar": [p(.bookmark, .view, 300), p(.bookmarksBar, .view, 100)],
        "bookmark.manager": [p(.bookmark, .view, 301), p(.bookmarksBar, .view, 101)],
    ]
}
